### ISSUE TITLE
[bug]: Unexpected token error

### ISSUE THREAD

**Issue by IgorGanapolsky** [zdharma/fast-syntax-highlighting#1]
### Environment

MacOS

### Expected behavior

Should be able to run 
> source ~/.zshrc

### Current behavior

When I run it, It gives an error:
> bash: ${${0:#$ZSH_ARGZERO}:-${(%):-%N}}: bad substitution
bash: ${${(M)0:#/*}:-$PWD/$0}: bad substitution
bash: typeset: -g: invalid option
typeset: usage: typeset [-afFirtx] [-p] name[=value] ...
bash: typeset: -g: invalid option
typeset: usage: typeset [-afFirtx] [-p] name[=value] ...
bash: typeset: -g: invalid option
typeset: usage: typeset [-afFirtx] [-p] name[=value] ...
bash: typeset: -g: invalid option
typeset: usage: typeset [-afFirtx] [-p] name[=value] ...
bash: typeset: -g: invalid option
typeset: usage: typeset [-afFirtx] [-p] name[=value] ...
bash: ${~FAST_WORK_DIR}: bad substitution
mkdir: : No such file or directory
bash: /Users/ganapolsky/.zsh/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh: line 129: syntax error near unexpected token `)'
bash: /Users/ganapolsky/.zsh/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh: line 129: `      () {'
ganapolsky-macbookpro:~ ganapolsky$ thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1017:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Steps to reproduce

# Create a `.zsh` directory to store our plugins in one place
mkdir ~/.zsh

# Clone repo to `~/.zsh/` directory
cd ~/.zsh && git clone git@github.com:zdharma/fast-syntax-highlighting.git

# Enable 'fast-syntax-highlighting' plugin in ZSH
echo "source $HOME/.zsh/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh" >> ~/.zshrc

# Reload ZSH
source ~/.zshrc

### Code snippet

eval "$(starship init zsh)"
source $HOME/.zsh/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

### Aditional information

Following the tutorial here:
https://tjay.dev/howto-my-terminal-shell-setup-hyper-js-zsh-starship/

### Self-service

- [X] I'd be willing to address this documentation request myself.

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/z-shell/community/blob/main/docs/CONTRIBUTING_GUIDELINES.md).

### Are you familiar with Contributor Covenant Code of Conduct?

- [X] I have read the [Contributor Covenant Code of Conduct](https://github.com/z-shell/zi/blob/main/docs/CODE_OF_CONDUCT.md).

### Contact Details

iganapolsky@gmail.com

**Comment by ss-o** [comment]
Hi :wave: 

This indicates that you running `zsh` script in a `bash` shell:

```bash
bash: ${${0:#
```

The tutorial has mistakes such as:

```shell
# Reload ZSH
source ~/.zshrc
```

Which does not reload the shell and simply sources the specified file.

Reload shell with:

```shell
exec zsh -il
```

---

I recommend checking the [Zi](https://z.digitalclouds.dev/docs/intro). :octocat: 

Sincerely,
