### ISSUE TITLE
Option highlighting for "command" broken

### ISSUE THREAD

**Issue by mgild** [zdharma/fast-syntax-highlighting#10]
<img width="148" alt="screen shot 2017-08-26 at 7 44 10 am" src="https://user-images.githubusercontent.com/6910981/29742364-c0d87a1e-8a32-11e7-8654-69beabc9d829.png">

-v showing up invalid while this is not the case

<img width="444" alt="screen shot 2017-08-26 at 7 44 23 am" src="https://user-images.githubusercontent.com/6910981/29742368-d2f87992-8a32-11e7-9587-b388e0cb21aa.png">

**Comment by psprint** [comment]
I've implemented correct highlighting, you could make a check, thanks for reporting.
