### ISSUE TITLE
Command substitution highlight does not nest

### ISSUE THREAD

**Issue by F-i-f** [zdharma/fast-syntax-highlighting#113]
The command substitution highlighting doesn't nest:
```
echo $(echo 1)
```
Here `$(echo 1)` is highlighted correctly with the secondary theme.
However in
```
echo $(echo $(echo 2) )
```
only the innermost `$(echo 2)` is highlighted with the secondary theme while the outermost `$(echo $(echo 2) )` doesn't have any highlighting.
Nested command substitutions are quite common, it would be nice if all of them could be highlighted.

**Comment by psprint** [comment]
This is rather a non-fix, as the optimizations that FSH has for handling the command substitutions with recursive highlighting impose a very limited freedom on the input.
