### ISSUE TITLE
flag-like strings after -- should not be highlighted as flags

### ISSUE THREAD

**Issue by anntzer** [zdharma/fast-syntax-highlighting#13]
Commonly, "--" is used to mark the end of the option list, so that e.g. `grep -- -foo ...` greps for the string `-foo`.  It seems like this is something that could easily be detected statically, and highlighting as flags turned off for such strings.

**Comment by psprint** [comment]
Good idea, I'll implement this, thanks

**Comment by psprint** [comment]
I've implemented this in (https://github.com/zdharma/fast-syntax-highlighting/commit/8c3e75ea5e408e7f6e06f54e07049c97763f11e5), it's release v1.15.

**Comment by anntzer** [comment]
Thanks, it works!
