### ISSUE TITLE
disable all underlining

### ISSUE THREAD

**Issue by theonlygusti** [zdharma/fast-syntax-highlighting#131]
This plugin is underlining all paths.

How do I turn off _all_  underlining (not just necessarily for paths, idk what else is underlined but I know that I don't want it to be)

**Comment by psprint** [comment]
I would create an overlay mini theme and overwrite the styles that use
underlines. Look at the Theme Guide

czw., 25 kwi 2019, 19:55 użytkownik George <notifications@github.com>
napisał:

**Comment by psprint** [comment]
So basically, the file `~/.config/fsh/overlay.ini` would look like this:

```ini
; overlay.ini
[paths]
path-to-dir   = magenta
```

Then just apply the overlay via `fast-theme XDG:overlay`. It will be always active, even after switching themes, enforcing its no-underline styles onto the theme's.

**Comment by theonlygusti** [comment]
I don't fully understand, but having configuration options is always a good thing?

Why is the option not this

```
[paths]
underline = no
```

Don't really understand the choice of option you've come up with, but having themes and configuration is a good thing

**Comment by psprint** [comment]
I understand your view – to have an option to disable the underline. However such an approach would require an additional code that would filter the styles of the theme. Such filtering is in general problematic. I think that when you'll get know FSH more you'll like the style/theme based approach.
