### ISSUE TITLE
pasting disables syntax highlighting until the keyboard is used again

### ISSUE THREAD

**Issue by theonlygusti** [zdharma/fast-syntax-highlighting#133]
Copy `hello` to the clipboard then type `echo ` at the command line and paste `hello`, the previously-green `echo` (syntax highlighted) becomes white.

Maybe linked to #132: when pasting text and using the keyboard while waiting for the paste to complete, the syntax highlighting is not reset.

**Comment by psprint** [comment]
This doesn't reproduce to me. As in #132, could you share some configuration, maybe the `.zshrc`?

**Comment by psprint** [comment]
I've added improvement patches so hopefully, this should be fixed.

**Comment by CallumHoward** [comment]
I can reproduce this I think. Here are some details:

FSH: #634ab24 
Emulator: macOS Terminal, also iTerm2 3.3.8, inside and outside Tmux
Zsh: 5.7.1
Using Oh-my-zsh.

The behaviour is, after pasting, the style is set to "reverse" for the pasted text. After moving the cursor or typing a character, the "revere" styling is removed.

Reproducible in:
no highlighting: No
Zsh Syntax Highlighting: Yes
Fast Syntax Highlighting: Yes

Using the default theme:
<img width="416" alt="Screen Shot 2019-12-30 at 12 58 50 pm" src="https://user-images.githubusercontent.com/7144420/71565592-2b078c80-2b04-11ea-9c21-0b1f9a43c563.png">
<img width="648" alt="Screen Shot 2019-12-30 at 12 59 50 pm" src="https://user-images.githubusercontent.com/7144420/71565595-4a061e80-2b04-11ea-834d-c2e83d39113b.png">

Possibly separate but related, when selecting text in the Zsh vi-mode, reverse styling is used.
If possible I would like a configuration option to not use "reverse" styling and instead be able to set the fg and bg. Perhaps this is not possible though?

**Comment by psprint** [comment]
By reproducing this you mean that the fix is working?

Configuring the pasting style is possible. I'll implement this, however, I don't know when.

**Comment by CallumHoward** [comment]
Sorry, I misread the original issue. The 'echo' always stays green for me.

**Comment by CallumHoward** [comment]
I can make a separate issue for the feature request if you like.

**Comment by psprint** [comment]
Yes that would be great.

**Comment by CallumHoward** [comment]
https://github.com/zdharma/fast-syntax-highlighting/issues/170
