### ISSUE TITLE
2 systems, same setup, different colors?

### ISSUE THREAD

**Issue by eikenb** [zdharma/fast-syntax-highlighting#134]
I have 2 Debian Buster systems, one I use directly the other over ssh. They have the exact same .zsh setup (rsynced over) using fast-syntax-highlighting. Same versions of zsh and related software. Neither has a custom theme selected.

On my main system everything works like it should. On the other system the colors are messed up. Things that are supposed to be default/white are red, when the background color is reset back to normal (from a background highlight), it goes red as well.  I'll attach a screen shot of the output of `fast-theme -t default` to show it.

Any thoughts at what might be wrong? Thanks.

![2019-05-01-193458_812x832_scrot](https://user-images.githubusercontent.com/722663/57054277-502bbe80-6c48-11e9-8ac9-0f1b291c2bdc.png)

**Comment by eikenb** [comment]
Figured it out. I'm using rxvt-unicode and until recently to enable 256 colors you needed to modify it's terminfo entry, I kept TERM named rxvt-unicode for better cross system compatibility. 

Anyways, getting rid of the modified terminfo entry and changing TERM to rxvt-unicode-256color brought the 2 systems in line with both working.

**Comment by psprint** [comment]
I'm glad that it has resolved

czw., 2 maj 2019, 20:32 użytkownik John Eikenberry <notifications@github.com>
napisał:
