### ISSUE TITLE
Bad math expression with literal ^@ NUL character

### ISSUE THREAD

**Issue by Juici** [zdharma/fast-syntax-highlighting#137]
When including the literal [NUL character ^@](https://en.wikipedia.org/wiki/Null_character) in the command line, all hell breaks loose.

When fast-syntax-highlighting is not installed the error is not reproducible. Also to note the same error does not occur when using zsh-syntax-highlighting.

To reproduce insert the character into the command line and try editing the command.

To insert the NUL character literal the keyboard sequence can be used:
<kbd>Ctrl</kbd>+<kbd>V</kbd>, <kbd>Ctrl</kbd>+<kbd>@</kbd>

Errors are produced when attempting to work with the NUL character and it causes key strokes to register incorrectly. It is also not possible to bring up a line from history which contains the NUL character.

Here are some examples along with their respective errors.

<details>
<summary><code>'^@</code></summary>
<pre>
-fast-highlight-process:811: bad math expression: operand expected at `'-__PBUFLE...'
-fast-highlight-process:814: bad math expression: operand expected at `''
-fast-highlight-process:814: bad math expression: operand expected at `''
</pre>
</details>

<details>
<summary><code>=^@</code></summary>
<pre>
-fast-highlight-process:814: bad math expression: operand expected at `='
-fast-highlight-process:814: bad math expression: operand expected at `='
</pre>
</details>

<details>
<summary><code>-^@</code></summary>
<pre>
-fast-highlight-process:814: bad math expression: operand expected at end of string
-fast-highlight-process:814: bad math expression: operand expected at end of string
</pre>
</details>

<details>
<summary><code>;^@</code></summary>
<pre>
-fast-highlight-process:814: bad math expression: empty string
-fast-highlight-process:814: bad math expression: empty string
</pre>
</details>

<details>
<summary><code>; ^@</code></summary>
<pre>
-fast-highlight-process:814: bad math expression: empty string
-fast-highlight-process:814: bad math expression: operand expected at end of string
</pre>
</details>

<details>
<summary><code>.^@</code></summary>
<pre>
-fast-highlight-process:811: bad floating point constant
-fast-highlight-process:814: bad floating point constant
-fast-highlight-process:814: bad floating point constant
</pre>
</details>

<details>
<summary><code>(^@</code></summary>
<pre>
-fast-highlight-process:811: bad math expression: ')' expected
-fast-highlight-process:814: bad math expression: ')' expected
-fast-highlight-process:814: bad math expression: ')' expected
</pre>
</details>

<details>
<summary><code>[^@</code></summary>
<pre>
-fast-highlight-process:811: bad output format specification
-fast-highlight-process:814: bad output format specification
-fast-highlight-process:814: bad output format specification
</pre>
</details>

<details>
<summary><code>print '^@</code></summary>
<pre>
-fast-highlight-process:811: bad math expression: illegal character: '
-fast-highlight-process:814: bad math expression: illegal character: '
</pre>
</details>

Errors also do not seem to occur when the NUL character is inside of `$(^@)`, but they do occur inside of <code>\`^@\`</code>.

**Comment by Juici** [comment]
I think the error occurs here: https://github.com/zdharma/fast-syntax-highlighting/blob/master/fast-highlight#L1170

**Comment by psprint** [comment]
The problem should be now fixed. Sorry for the delay and thanks!
