### ISSUE TITLE
Comments are always just black and unreadable on dark background color schemes.

### ISSUE THREAD

**Issue by spielkind** [zdharma/fast-syntax-highlighting#138]
Comments are always just black and unreadable on dark background color schemes.
OS: ArchLinux
ZSH: 5.7.1
Terminal: gnome-terminal/terminator
Version: r621.25f81d7-1

![solarized_dark](https://user-images.githubusercontent.com/4437264/58968338-2d944480-87b6-11e9-80b1-612c821c0b04.png)

**Comment by psprint** [comment]
Did you try themes? The themes `sv-orple`, `sv-plant` have different colour (violet and green) for comments, and `q-jmnemonic` has quite light gray for it. Set the themes with:

```zsh
fast-theme sv-orple
etc.
```

**Comment by mihai-dinu** [comment]
Had the same problem, but I didn't really like the other themes that much. So I changed the default theme, which is pretty easy. You just need to update the `default.ini` theme with `comment = 243` (light gray for comments). 

Or a one-liner that works if you installed the plugin with zplugin (e.g. the recommended way)
```shell
sed -iE 's/\(comment\s*=\).*$/\1 243/' ~/.zplugin/plugins/zdharma---fast-syntax-highlighting/themes/default.ini
```

**Comment by psprint** [comment]
Ah yes, updating the theme.. you can accomplish this by creating a *theme-overlay*. Create a file:

```zsh
% mkdir ~/.config/fsh
% vim ~/.config/fsh/overlay.ini
```

with contents:

```ini
; overlay.ini
[base]
comment=241
```

Then, issue in terminal:
```zsh
% fast-theme XDG:overlay
```

and that's it, the keys from the `overlay.ini` are put onto the keys from any active theme :)
