### ISSUE TITLE
Use math-mode highlighting in `zcalc`

### ISSUE THREAD

**Issue by xPMo** [zdharma/fast-syntax-highlighting#14]
When launching `zcalc`, syntax highlighting still behaves as if in normal zle.  Since math-mode highlighting exists, supporting zcalc seems very reasonable.

The variable `$ZCALC_ACTIVE` is set to rpn (reverse polish notation) or 1 when `zcalc` is running, and unset otherwise.

**Comment by psprint** [comment]
Thanks, this was sufficient to enable math highlighting for zcalc. 
![fsyh-zcalc](https://user-images.githubusercontent.com/6049288/40429627-6d00c306-5ea3-11e8-9e55-f07386001944.png)
