### ISSUE TITLE
-fast-whatis-chroma-callback:3: @zts-read-all: function definition file not found

### ISSUE THREAD

**Issue by leogx9r** [zdharma/fast-syntax-highlighting#141]
These errors frequently pop up when running some commands such as `man` along with every character typed after the space. They've also happened for other commands but I can't immediately recall which ones.

![image](https://user-images.githubusercontent.com/40126089/59642254-bbc3df80-9153-11e9-986e-ff34a6a21c4c.png)

Recently upgraded this to `r670.21f52d8-1` from the [AUR](https://aur.archlinux.org/packages/zsh-fast-syntax-highlighting-git) on Arch Linux. Prior version was quite old aka from commit 868812a

**Comment by leogx9r** [comment]
I've confirmed the file `@zts-read-all` is not present in `/usr/share/zsh/plugins/fast-syntax-highlighting/` due to the install script only targeting files with the prefixes `fast-`, `_fast-` and `-fast` in the root folder and the `chroma` and `themes` folders.

Modifying the build script seems to fix this issue.

Perhaps you should consider renaming `@zle-read-all` to have a consistent prefix like the other files?

Feel free to close this if you don't decide to change the name.

**Comment by psprint** [comment]
Thanks, I've renamed the file to follow the -fast-* convention. Does the issue go away?

**Comment by leogx9r** [comment]
Yes, I've just confirmed 695db8c fixes the issue. Thanks a lot.

**Comment by psprint** [comment]
n/p :)
