### ISSUE TITLE
How to disable underline for path/path-to-dir

### ISSUE THREAD

**Issue by elimpnick** [zdharma/fast-syntax-highlighting#142]
Hi,

I'm trying to disable underline and magenta for `path` and `path-to-dir` from within my `.zshrc` file.  I'm using `zplug`.  It seems the following is not working:

```
if zplug check 'zdharma/fast-syntax-highlighting'; then
    # Disable underline of paths
    FAST_HIGHLIGHT_STYLES[path]='none'
    FAST_HIGHLIGHT_STYLES[path-to-dir]='fg=blue'
fi
```

What would be the right way (without making a theme)?

**Comment by psprint** [comment]
Your method should work. Make sure that you don't have any theme set by running `fast-theme --reset`.

**Comment by elimpnick** [comment]
Thanks for the quick answer, that actually fixed it!
