### ISSUE TITLE
Commands in backticks are not highlighted

### ISSUE THREAD

**Issue by lilydjwg** [zdharma/fast-syntax-highlighting#143]
This highlights as expected:

```
echo $(ls)
```

But this doesn't (the backtick part is white / default):

```
echo `ls`
```

**Comment by psprint** [comment]
Thanks! I've added the highlighting to the backticks, it should be working now.

**Comment by lilydjwg** [comment]
Thanks, it mostly works, but during typing:

```
echo `
```

The first letter will be highlighted as non-existent.

**Comment by psprint** [comment]
The issue has been fixed by another patch. Thanks!
