### ISSUE TITLE
when input like `man 5 terminfo`, it swallow the previous line

### ISSUE THREAD

**Issue by pre1ude** [zdharma/fast-syntax-highlighting#145]
when input `man 5 terminfo`, after you input `man 5`, and then you stroke the char t, the previous line will be swallowed!, keep stroke the chars left, and more lines are swallowed

**Comment by psprint** [comment]
Yea I confirm that I'm reproducing this, I'll look at this tomorrow.

**Comment by hurricanehrndz** [comment]
@psprint 

Thanks, seeing the same issue.

**Comment by psprint** [comment]
The issue has been fixed! Please check :)
