### ISSUE TITLE
Git commit message length should not be limited

### ISSUE THREAD

**Issue by zl-kolev** [zdharma/fast-syntax-highlighting#149]
As it is strictly individual and/or company imposed, I suggest the limit of the git commit message is left unlimited (or configurable). I have read this issue (https://github.com/zdharma/fast-syntax-highlighting/issues/25), but I really think people should have the freedom to decide how long their commit messages should be, or be unlimited at best.

**Comment by psprint** [comment]
I've added configuring of it, via the field `FAST_HIGHLIGHT[git-cmsg-len]`, so an example use of it is `FAST_HIGHLIGHT[git-cmsg-len]=120`.

**Comment by zl-kolev** [comment]
Can you please point me to where this setting should be placed?

**Comment by psprint** [comment]
It can be placed after loading the plugin in `.zshrc`. Or in the `atload''` clause if using Zplugin. It can be also placed before loading the plugin if the hash will be defined first by `typeset -g FAST_HIGHLIGHT`. Sorry for the inconvenience.

**Comment by zl-kolev** [comment]
Not really sure how to proceed. I've tried putting it at the end of `.zshrc`, but I don't get any result. I'm using Antibody (https://getantibody.github.io/) and I'm dynamically loading your plugin, so I have `source <(antibody init)` and `antibody bundle < ~/.zsh_plugins` at the end of `.zshrc`.

**Comment by psprint** [comment]
You've definitely should see the result, as demonstrated here: https://asciinema.org/a/yD9iAOIBiMYUaEtCVsa4rVj9s

**Comment by zl-kolev** [comment]
I'm using Ubuntu 18.04, not macOS. Probably this is the reason my attempt fails.

**Comment by psprint** [comment]
I would bet on something else. Maybe the plugin didn't update properly?

**Comment by zl-kolev** [comment]
That's it! I can't believe this is the answer, I just installed it yesterday. Problem solved! Thank you!

**Comment by psprint** [comment]
n/p, thanks for the report!
