### ISSUE TITLE
Highlight command substitution

### ISSUE THREAD

**Issue by noscript** [zdharma/fast-syntax-highlighting#15]
![image](https://user-images.githubusercontent.com/717109/37476428-cbebec12-287d-11e8-946f-f5653daf610b.png)

**Comment by psprint** [comment]
Extended this so that **secondary theme** is used for code inside $() !

![cmdsubst](https://user-images.githubusercontent.com/6049288/40842472-4a387d16-65ae-11e8-88a5-921fcb4817af.png)

**Comment by Arkanosis** [comment]
That's really great!

Highlighting of the closing parenthesis is incorrect if following a string with no space in between, though, see:

![command](https://user-images.githubusercontent.com/124583/41042967-39ad4776-69a3-11e8-988b-20425fc42b3c.png)

Thanks!

**Comment by noscript** [comment]
Works great!
