### ISSUE TITLE
errors when typing a specific string: "unknown condition: -v"

### ISSUE THREAD

**Issue by hoshsadiq** [zdharma/fast-syntax-highlighting#152]
Hello, I am currently running this using zplugin in centos, but I'm unable to type out the following:

```
token="$(cat ~/.terraformrc | awk -F'"' '{print $3}')"
```

It stops as soon as I type the 3 in the above command.

The error I get is:

```
-fast-highlight-process:256: unknown condition: -v
```

Host details:
Centos7
zsh 5.1

**Comment by psprint** [comment]
If you upgrade to Zsh 5.3 the problem will go away. I'm considering the withdrawal of the patch that introduced the fairly fresh construct.

**Comment by hoshsadiq** [comment]
Cool will do! If not, it's worth adding a minimum requirements in the README. I looked for it but didn't find any.

**Comment by hoshsadiq** [comment]
So this seems to be harder than expected. Is there a way to add backwards compatibility by any chance? Or are you not planning to do so and/or is too much effort to do so?

**Comment by psprint** [comment]
I've restored the backwards compatibility.

**Comment by hoshsadiq** [comment]
Thank you very much mate!
