### ISSUE TITLE
Breaks with zsh-5.3.1

### ISSUE THREAD

**Issue by vaeth** [zdharma/fast-syntax-highlighting#156]
Since a few commits, on zsh-5.3.1, instead of a readable command line, only errors like the following appear at every keystroke:

_zsh_highlight:26: command not found: -fast-highlight-init
_zsh_highlight:27: command not found: -fast-highlight-process
_zsh_highlight:26: command not found: -fast-highlight-init
_zsh_highlight:27: command not found: -fast-highlight-process

On zsh-5.7.1, there are no such problems.

**Comment by psprint** [comment]
I've tested zsh 5.3.1 and observe no such problem. Could you debug it? I can provide some debug steps later today if yes.

**Comment by vaeth** [comment]
I thought that it is trivial to reproduce, but now I realize that it is related with the way I sourced it:
```
path=(several paths where fast-syntax-highlighting might reside) source fast-syntax-highlighting.plugin.zsh >&/dev/null
```
This runs smoothly since ages on my gentoo system, but it broke on my guest account  in Debian:
% zsh --version
zsh 5.3.1 (x86_64-debian-linux-gnu)

Feel free to close as invalid.

**Comment by psprint** [comment]
This is a pretty non-standard way of loading FSH. I'm afraid that not much can be done to aid it.
