### ISSUE TITLE
Completion of chroma/-*

### ISSUE THREAD

**Issue by vaeth** [zdharma/fast-syntax-highlighting#157]
On my system, if I type chroma/[TAB], I get completion offered for chroma/-alias.ch chroma/-autoload.ch etc.

I conjecture that somehow the path to chroma is leaked to the completion system and simultaneously the .ch is for some reason recognized as an executable extension, though especially for the latter I found no obvious reason.

**Comment by psprint** [comment]
How does it manifest that the files are seen as executable ones? Screenshot maybe?

**Comment by vaeth** [comment]
In my completion configuration, I expected that chrom[TAB][TAB] essentially expands only to chromium, but I get:
```
% chrom[TAB][TAB]
chroma/-alias.ch
(external command)
(shell function)
(alias)
chroma/-alias.ch      chroma/-docker.ch      chroma/-git.ch     chroma/-lab.ch    chroma/-node.ch        chroma/-printf.ch  chroma/-source.ch      chroma/-vim.ch      chroma/main-chroma.ch
chroma/-autoload.ch   chroma/-example.ch     chroma/-grep.ch    chroma/-make.ch   chroma/-ogit.ch        chroma/-ruby.ch    chroma/-ssh.ch         chroma/-whatis.ch   chromedriver                        
chroma/-autorandr.ch  chroma/-fast-theme.ch  chroma/-hub.ch     chroma/-nice.ch   chroma/-perl.ch        chroma/-scp.ch     chroma/-subcommand.ch  chroma/-which.ch    chromium                            
chroma/-awk.ch        chroma/-fpath_peq.ch   chroma/-ionice.ch  chroma/-nmcli.ch  chroma/-precommand.ch  chroma/-sh.ch      chroma/-subversion.ch  chroma/-zplugin.ch  chromium-browser
```

**Comment by psprint** [comment]
Ah, yes, that's because the chroma functions are auto-loaded with the directory in their name. That's a good catch, I think that I'll be willing to rename the directory to `_chroma` to prevent this from happening. Maybe anyone interested in accomplishing a Hacktoberfest 2019 step with such pull-request?

**Comment by psprint** [comment]
I thought that this shouldn't wait and renamed the functions – from `chroma/*` to `:chroma/*`, according to an emerging (currently only my own) methodology of preceding the hooks' names with a colon.
