### ISSUE TITLE
zsh 5.7.1 crashed with fast-syntax-highlighting + prezto

### ISSUE THREAD

**Issue by skywind3000** [zdharma/fast-syntax-highlighting#158]
each time when I trying to input a hyphen `-` after:

```
git commit {cursor}
```

zsh crashed like:

```
git commit Segmentation fault (core dumped)
```

and it works well when I disable fast-syntax-highlighting

**Comment by mthornba** [comment]
I'm seeing the same behaviour. The following git commands create a seg fault when the - character is typed:

`git merge -`
`git commit -`
`git pull -`

**Comment by psprint** [comment]
The issue is fixed on the master branch – for the details see #146.
