### ISSUE TITLE
Precommand chroma not caught

### ISSUE THREAD

**Issue by mustaqimM** [zdharma/fast-syntax-highlighting#161]
If I type this, I get highlighting:
![2019-10-18_06-36](https://user-images.githubusercontent.com/24436622/67066246-2ff1ac80-f161-11e9-810d-39a24b4e19a4.png)

But for a different precommand there is no chroma highlighting:
![2019-10-18_06-37](https://user-images.githubusercontent.com/24436622/67066247-32540680-f161-11e9-8123-e09292b534cb.png)

**Comment by psprint** [comment]
That's a little weird. I must ask: is there a `sudo` command on the system? What does `which sudo` show?

**Comment by mustaqimM** [comment]
@psprint 
```zsh
$ which sudo
/bin/sudo

$ which doas
/bin/doas
```

Both are in the bin dir

**Comment by psprint** [comment]
And what does the following output:

```zsh
print $commands[sudo]
type -w sudo
```
?

**Comment by jelinekto** [comment]
I'm guessing the red underlined text doesn't mean there's something wrong with `sudo` - rather it's simply @mustaqimM 's colorscheme highlighting his precommands.

The reason why `sudo` and `doas` each have different highlighting is that `doas` isn't considered a precommand at all (or that's my guess based on `grep`ping through the repo). Which is the issue that brings me here, by the way.

**Comment by mustaqimM** [comment]
@psprint I set the style of the precommand as shown with the sudo example, doas doesn't follow the style for some reason.  

```zsh
typeset -gA FAST_HIGHLIGHT_STYLES
FAST_HIGHLIGHT_STYLES[alias]="fg=012"
FAST_HIGHLIGHT_STYLES[path]="fg=blue"
FAST_HIGHLIGHT_STYLES[path-to-dir]="fg=blue,underline"
FAST_HIGHLIGHT_STYLES[suffix-alias]="fg=012"
FAST_HIGHLIGHT_STYLES[builtin]="fg=012"
FAST_HIGHLIGHT_STYLES[function]="fg=012"
FAST_HIGHLIGHT_STYLES[precommand]="fg=red,bg=black,underline,bold"
FAST_HIGHLIGHT_STYLES[command]="fg=012"
FAST_HIGHLIGHT_STYLES[commandseparator]="fg=012"
FAST_HIGHLIGHT_STYLES[comment]="fg=011,bold,italic"
FAST_HIGHLIGHT_STYLES[single-quoted-argument]="fg=011"
FAST_HIGHLIGHT_STYLES[double-quoted-argument]="fg=011"
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument]="fg=011"
FAST_HIGHLIGHT_STYLES[single-hyphen-option]="fg=yellow"
FAST_HIGHLIGHT_STYLES[double-hyphen-option]="fg=215"
```

Here's my entire [zshrc](https://raw.githubusercontent.com/mustaqimM/dotfiles/master/.zsh/.zshrc)

**Comment by psprint** [comment]
@mustaqimM: I've updated the code to recognize `doas` as a precommand modifier.
