### ISSUE TITLE
Crash on zrecompile fpath files 

### ISSUE THREAD

**Issue by rjcoelho** [zdharma/fast-syntax-highlighting#166]
Because we are adding non zsh files to fpath. See https://github.com/unixorn/awesome-zsh-plugins/pull/851

`re-compiling fast-syntax-highlighting.zwc: zrecompile:21: parse error`

**Comment by psprint** [comment]
The error is about recompiling the byte-code file, i.e.: the result of the previous compilation. Such files shouldn't be passed to z(re)compile.
