### ISSUE TITLE
input after "ruby -e" is little laggy

### ISSUE THREAD

**Issue by seiyeah78** [zdharma/fast-syntax-highlighting#171]
When type after ```ruby -e ```, render performance is not good.

try ```ruby -e```
![lag](https://user-images.githubusercontent.com/6185139/72170856-fc978480-3414-11ea-84ad-82475bc691e5.gif)

other
![not_lag](https://user-images.githubusercontent.com/6185139/72170862-ff927500-3414-11ea-969c-a6f0b045cf8b.gif)

do you have any solutions?

**Comment by psprint** [comment]
The reason is that the Ruby chroma is evaluating the code passed to the `-e` option. You can disable the chroma by running:

```zsh
FAST_HIGHLIGHT[chroma-ruby]=
```

or in case of running Zplugin:

```zsh
 zplugin wait=0 lucid notify light-mode \
      atinit="ZPLGM[COMPINIT_OPTS]=-C; zpcompinit; zpcdreplay" \
      atload="FAST_HIGHLIGHT[chroma-ruby]=" for \
          zdharma/fast-syntax-highlighting
```

**Comment by seiyeah78** [comment]
thanks. it works!

**Comment by psprint** [comment]
Great!
