### ISSUE TITLE
Bug: wrong highlight of svn command

### ISSUE THREAD

**Issue by Aloxaf** [zdharma/fast-syntax-highlighting#173]
![image](https://user-images.githubusercontent.com/17017672/72412880-6dd68f00-37a9-11ea-9fd1-34feb49e0fd4.png)

`git bisect` tells me that 6440fd970a2a1b3d3420fee5523ca4a622eb0e7d is the first bad commit, very confusing.

**Comment by psprint** [comment]
It's almost fixed now, thanks! The only thing that's left is the lack of highlighting of the `svn` word at first use.

**Comment by psprint** [comment]
Ok, it's fixed now, thanks again!

**Comment by Aloxaf** [comment]
Amazing speed! Thanks for your great work!
