### ISSUE TITLE
"Command not found" on man/whatis chroma 

### ISSUE THREAD

**Issue by maxzinkus** [zdharma/fast-syntax-highlighting#174]
https://github.com/zdharma/fast-syntax-highlighting/blob/a5a4bb4181fe87afa16a331779fb70761afd6eea/:chroma/-whatis.ch#L21

`-fast-whatis-chroma-callback:6: command not found: -fast-zts-read-all`

**Comment by maxzinkus** [comment]
I think commit https://github.com/zdharma/fast-syntax-highlighting/commit/23033dfbf8f485adc0bfdcb80ebb1b87fdb5f540 caused this, as it just started happening.

**Comment by psprint** [comment]
Thanks!

**Comment by maxzinkus** [comment]
Thank you! This software is awesome, as was your response time!

**Comment by psprint** [comment]
You're welcome!
