### ISSUE TITLE
man command is slow

### ISSUE THREAD

**Issue by seagle0128** [zdharma/fast-syntax-highlighting#179]
While using man command with `fast-syntax-highlighting`, it's slow to autocomplete. No issue  with `zsh-syntax-highlighting`.

**Comment by psprint** [comment]
Which operating system and Zsh version?

**Comment by nathanshelly** [comment]
Running into this same issue, after typing `man` things hang briefly before I can type again.

OS - `macOS Catalina v10.15.3 (19D76)`
Zsh version - `zsh 5.8 (x86_64-apple-darwin19.3.0)`

**Comment by Caagr98** [comment]
Same for me: after writing `man`, any additional characters take about 0.2s to appear. `zsh 5.8 (x86_64-pc-linux-gnu)` on Arch.

**Comment by sashaweiss** [comment]
Seeing the same behavior, with sometimes multi-second hangs. `zsh 5.7.1 (x86_64-apple-darwin18.2.0)`, `macOS Catalina 10.15.2 (19C57)`.

**Comment by seagle0128** [comment]
Sorry for the late reply. Here is my env.

```
macOS Catalina 10.15.3
zsh 5.7.1 (x86_64-apple-darwin19.0)
```

I believe it also happens on other versions.

**Comment by psprint** [comment]
You can disable the `man` chroma by doing: `FAST_HIGHLIGHT[chroma-man]=` after loading the plugin, possibly in the `atload''` ice if using Zinit/

**Comment by eggeek** [comment]
Same for me, first time of typing`man` takes 2s. My version is `zsh 5.7.1 (x86_64-apple-darwin19.0)`

**Comment by psprint** [comment]
On the current HEAD?

**Comment by eggeek** [comment]
The problem has been fixed after `git pull`, thanks.
I used to use `upgrade_oh_my_zsh` to update plugins, 
while it turns out that third-party plugins won't be updated.

**Comment by seagle0128** [comment]
I checked today, and the issue still exists.

**Comment by horta** [comment]
Same here.

**Comment by horta** [comment]
After having typed man, it sometimes take 5s to let me type any other character.

Git is also take a bit to complete.

```
base ❯ uname -a    
Darwin horta-ml 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

~
base ❯ zsh --version
zsh 5.7.1 (x86_64-apple-darwin19.0)
```

**Comment by yanzhang0219** [comment]
Same here. Using bare zsh and when I type man, it will take 1-2 seconds to type characters. Thanks.

**Comment by agoose77** [comment]
I can't reproduce this after performing `zinit update` and `zinit self-update` today. However, I have a similar problem with `make`, which disappears (along with the highlighting of course) if I use the ice `atload"FAST_HIGHLIGHT[chroma-make]="`

**Comment by horta** [comment]
The problem persists for me.

**Comment by yanzhang0219** [comment]
@psprint Any updates and fixes on this? Thanks.

**Comment by psprint** [comment]
The issue should be now fixed.

**Comment by seagle0128** [comment]
It looks fine to me. Thanks!

**Comment by sashaweiss** [comment]
I've updated `fast-syntax-highlighting` to current `master`, and have run `zinit self-update`. Unfortunately, I still see this issue.

Would love to help debug, if there's any logs or information I can provide!

**Comment by psprint** [comment]
@sashaweiss Is your system OS X?

**Comment by sashaweiss** [comment]
Yeah, I'm on OS X 10.15.5 running `zsh` from Homebrew (`zsh 5.8 (x86_64-apple-darwin19.3.0)`).

**Comment by psprint** [comment]
Could you show:

```zsh
uname -a
print $FAST_HIGHLIGHT[chroma-man]
```
?

**Comment by seagle0128** [comment]
A little bit slow for the first time using `man` command.

Mine is 
```shell
 ~ % uname -a
Darwin nds-MacBook-Pro.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
 ~ % print $FAST_HIGHLIGHT[chroma-man]
→chroma/-whatis.ch
```

**Comment by psprint** [comment]
The issue should be definitely solved now.

**Comment by seagle0128** [comment]
@psprint Same issue and same results.

Is `[[ $OSTYPE == (#i)darwin ]]` correct? In my env, `$OSTYPE` is `darwin19`. I tried `[[ $OSTYPE == darwin* ]]` and ```[[ `uname -s` == Darwin ]]```, all work fine.

**Comment by psprint** [comment]
Thanks, it's fixed now.

**Comment by seagle0128** [comment]
@psprint Unfortunately `[[ $OSTYPE == (#i)darwin* ]]` doesn't work for me. Why using `(#i)` here?

**Comment by psprint** [comment]
Ah, it will not work if the option `extendedglob` isn't set. That's the source of the all problems in this issue. Ok, I've removed the flag, the `$OSTYPE` will be lowercase anyway (`(#i)` means case-insensitive matching), so finally the issue should be now resolved.

**Comment by seagle0128** [comment]
Cool! It works well now. Thanks!
