### ISSUE TITLE
Testing performance request

### ISSUE THREAD

**Issue by psprint** [zdharma/fast-syntax-highlighting#18]
@ludanxer, I've put some effort to optimize f-sy-h, can I ask you to do a real world test and paste the long links into fast-syntax-highlighted prompt? It's a situation when you know which url is slow under z-sy-h, I don't have such urls. (I'm referring to issue you've opened at zsh-syntax-highlighting).

**Comment by ludanxer** [comment]
Thanks for your effort !!!

I've disabled all other zsh plugins and tried several links, `f-sy-h` does work faster than `zsh-syntax-highlighting`. But there is still an apparent delay while facing large input. Adding `export ZSH_HIGHLIGHT_MAXLENGTH=60` to stop parse and highlight any large input is still the best solution I get by now.

I'm sorry I'm not very familiar with shell, I don't know how to time it accurately. So I leave you one fixed(I changed a few letter randomly to avoid any possible copyright problem) magnet url below : 

`magnet:xt=urn:btih:27ce0eae79c56e602c2b3d6015558f9113d408c6&tr=udp://9.rarbg.to:2710/announce&tr=udp://9.rarbg.me:2710/announce&tr=http://tr.cili011.com:8070/announce&tr=http://tracker.trackerfix.com:80/announce&tr=udp://open.demonii.com:1337&tr=udp://tracker.opentrack.org:1337/announce&tr=udp://p4p.arenabg.com:1337&tr=wss://tracker.openwebtorrent.com&tr=wss://tracker.btorrent.xyz&tr=wss://tracker.fastcast.nz`

**Comment by psprint** [comment]
Thank you. At my local OS X box the link pastes instantly. For me problems disappeared when zsh-autosuggestions plugin switched to async-architecture. However on a SSH box, the delay does occur. It is shorter for f-sy-h than for z-sy-h, the difference isn't that large, however I'm quite happy that I can limit unpleasant side-effects by optimizing. Thanks for the link.
