### ISSUE TITLE
Use of completion menu causes all highlighting to disappear

### ISSUE THREAD

**Issue by marlonrichert** [zdharma/fast-syntax-highlighting#189]
Given:
* `zsh/complist` has been loaded.
* `compinit` has been run.

When:
1. I type something
1. I invoke any widget that makes completion listing appear.
   * Then: Highlighting disappears
1. I use menu selection to select a completion.
   * Then: Highlighting reappears
1. I press Return to insert the suggestion.
   * Then: Highlighting disappears again

This is especially a problem with my [plugin `zsh-autocomplete`](https://github.com/marlonrichert/zsh-autocomplete), which automatically lists completions, [causing the highlighting to flicker on and off while typing](https://github.com/marlonrichert/zsh-autocomplete/issues/29#issuecomment-632267007).

Is this something you can fix? Or is there some way I can work around this in my plugin?

If I set `REGION_ACTIVE=1` or `REGION_ACTIVE=2`, then the highlighting does not disappear, but everything is rendered in standout mode.

**Comment by marlonrichert** [comment]
I just checked and https://github.com/zsh-users/zsh-syntax-highlighting does _not_ suffer from this problem. There, the highlighting stays active, no matter what I do.

**Comment by FreddieOliveira** [comment]
@marlonrichert, pls test this PR: #198 and check if the issue is fixed. I don't personally use your `zsh-autocomplete`, but I use `fzf-tab` which was suffering from similar issue.

**Comment by marlonrichert** [comment]
@FreddieOliveira Sorry, but this does not solve my case. However, it appears @psprint has already fixed this.
