### ISSUE TITLE
[Question] More releases!

### ISSUE THREAD

**Issue by Snuggle** [zdharma/fast-syntax-highlighting#19]
Hey! I'd like to get this packaged for [Solus](https://en.wikipedia.org/wiki/Solus_(operating_system)), to replace `zsh-syntax-highlighting`, but we'd need you guys to actually keep on top of making releases on [your releases page](https://github.com/zdharma/fast-syntax-highlighting/releases). (We need a tarball to actually package, so we can have static versions of your package.)

Once you've made a recent release that's not over a year old, I can make a request for this to get packaged, if that's cool with you guys. c:

I think this is a much better alternative to zsh-syntax-highlighting and I'd love to see this on my distro of choice as an easy-to-install package.

Anyways, thank you for reading and I hope you have an awesome day!

**Comment by psprint** [comment]
I would be very happy if FSH would be packaged for Solus, it looks like an interesting distribution. I'll take a look into doing more explicit releases than tag names. After you've entered the issue but there was no body yet (I think you added it later, that's why I'm replying after a while), I made a quick tag `v1.1`, not sure if such release is sufficient?

**Comment by Snuggle** [comment]
Ahah! Yes, thank you so much! Most of our packages require having a tarball to use as a source and we often use GitHub releases/tags to do so. (Though anywhere that a tarball is available is fine.)
![image](https://user-images.githubusercontent.com/26250962/40742643-106ccb68-6447-11e8-9b6a-0ac86e72b403.png)

Apologies for making the issue without a body, too. I accidentally pressed enter after typing the title and had to edit it afterwards. Woops.

I have made a request for `fast-syntax-highlighting` to [get added on the Solus dev tracker](https://dev.solus-project.com/T6471) and I'll add an update to this issue if/when it gets packaged. Thank you so much. :slightly_smiling_face:
