### ISSUE TITLE
ANSI-C-like strings

### ISSUE THREAD

**Issue by smhmd** [zdharma/fast-syntax-highlighting#190]
Using ANSI-C-like strings (`$'...'`) in zsh to be able to escape characters,  `fast-syntax-highlighting` does not treat the string as a string but tries to syntax highlight it:

```fish
$ echo " ' () (["   # double quotes
 ' () ([
```
```fish
$ echo $' \' () (['  # ANSI-C-like string
 ' () ([
```

![image](https://user-images.githubusercontent.com/46059092/83281959-cd6d8e00-a1d0-11ea-9d98-e5bed519b3fb.png)

Idealy, the second command's `() ([` substring should be completely orange, I think.

**Comment by psprint** [comment]
It is implemented, thanks.

**Comment by smhmd** [comment]
Works great. Thank you.

![image](https://user-images.githubusercontent.com/46059092/83342856-f9c9fd00-a2eb-11ea-9586-654f1506471b.png)
