### ISSUE TITLE
FAST_HIGHLIGHT: assignment to invalid subscript range

### ISSUE THREAD

**Issue by numToStr** [zdharma/fast-syntax-highlighting#195]
I am having this issue because of this line `FAST_HIGHLIGHT[git-cmsg-len]=100` in my `.zshrc`. This issue is only occurring on my remove server not but on my local machine. Though I have the same `.zshrc` on both of my machine.

**Comment by psprint** [comment]
It appears there is a `typeset -gA FAST_HIGHLIGHT` missing before the assignment?

**Comment by numToStr** [comment]
I did that and syntax highlighting goes off. I need to run `fast-theme -t spa` to set the theme, though I have `FAST_THEME_NAME=spa` in my `.zshrc`.

Is this expected?

**Comment by psprint** [comment]
Yes, the `fast-theme` call is needed, it generates the `current_theme.zsh` and `secondary_theme.zsh` in `$FAST_WORK_DIR` from the `ini` defs.

**Comment by numToStr** [comment]
Ohh. I get it now. Thanks for the clarification.

**Comment by numToStr** [comment]
Hi @psprint, Sorry for bothering you. Is there any way to automate the `fast-theme` call? I am making some dotfiles for my setup and I don't want to call `fast-theme` manually.
