### ISSUE TITLE
max nested funct level with zsh-vim-mode and powerline10k 

### ISSUE THREAD

**Issue by Artturin** [zdharma/fast-syntax-highlighting#199]
this has been happening since #198 (thanks for that btw)
i checked out 865566ce48cfd9bb5cdbaf5b1a74b0a675f4ccd4 and it does not happen 
```
zinit light softmoth/zsh-vim-mode

zinit ice depth=1; zinit light romkatv/powerlevel10k
[[ ! -f $ZDOTDIR/p10k.zsh ]] || source $ZDOTDIR/p10k.zsh

zinit wait lucid for \
 atinit"ZINIT[COMPINIT_OPTS]=-C; zicompinit; zicdreplay" \
    zdharma/fast-syntax-highlighting
```
after opening a new terminal and running any command i get 
```
azhw:zle-line-init:8: maximum nested function level reached; increase FUNCNEST?
```

if i add 
```
atload"!_zsh_autosuggest_start" \
zsh-users/zsh-autosuggestions
``` 
to after fsh i get 
```
_zsh_autosuggest_bound_1_user:_p9k_widget_zle-line-init:9: maximum nested function level reached; increase FUNCNEST?
```

if i comment either `zsh-vim-mode` or `powerlevel10k` i no longer get those messages

if i use turbo with either of them it does not happen either

ping @FreddieOliveira

**Comment by FreddieOliveira** [comment]
Hmm, I cannot reproduce this. I do use `powerlevel10`, but not `zsh-vim-mode`. However, I use a similar [vim-zsh configuration.](https://github.com/FreddieOliveira/dotfiles/blob/master/zsh/.oh-my-zsh/custom/plugins/vi-mode/vi-mode.plugin.zsh)

Could you share your `.zshrc` file and post which version of zsh and plugins you're using?

**Comment by Artturin** [comment]
this doesn't happen on a new user with the same zsh config so it must be something on my user acc.
I'll close this since I've found a workaround which is to use turbo with zsh-vim-mode, i wasn't using it before because i had bindkeys and didn't know how to apply them when using turbo.
```
zinit wait lucid  for \
    atload'
        bindkey -M vicmd "/" history-search-multi-word
        bindkey "^[OA" up-line-or-beginning-search
        bindkey "^[OB" down-line-or-beginning-search
        bindkey -M vicmd "k" up-line-or-beginning-search
        bindkey -M vicmd "j" down-line-or-beginning-search
        ' softmoth/zsh-vim-mode
```

**Comment by psprint** [comment]
It doesn't reproduce on the new box probably because I've reverted the line-init patch.
