### ISSUE TITLE
Implicit cd has directories shown as red

### ISSUE THREAD

**Issue by mgild** [zdharma/fast-syntax-highlighting#2]
Using the implicit cd feature i.e. just typing directory names to jump to them
Using: zsh 5.2 (x86_64-apple-darwin16.0)

**Comment by strindberg** [comment]
This should also work for directory aliases:

pr="$HOME/projects"
setopt AUTO_CD

> ~pr  <--- not red

**Comment by psprint** [comment]
Fixed, thanks. I didn't limit this functionality to only AUTO_CD being set, for simpler code.
