### ISSUE TITLE
[bug]: Tab completion breaks syntax highlighting

### ISSUE THREAD

**Issue by alterae** [zdharma/fast-syntax-highlighting#2]
### Environment

OSTYPE=darwin21.0 CPUTYPE=arm64 / MACHINE_TYPE=x86_64 ZSH_VERSION=5.8.1

### Expected behavior

All tokens in the input line should receive syntax highlighting no matter what.

### Current behavior

If a token is completed by pressing the TAB key, it will display without syntax highlighting until more keyboard input is provided. 

### Steps to reproduce

- Begin typing the name of a program that is in the PATH (for this example, I will use `neofetch`). Type only part of the name, so that it is syntax highlighted in red (`neof`). 
  
<img width="74" alt="image" src="https://user-images.githubusercontent.com/27498421/175318649-3dba7c2b-374b-46b9-b021-8d01ea3d8e5a.png">

- Press the tab key to complete the command. It will now be displayed in white. 

<img width="116" alt="image" src="https://user-images.githubusercontent.com/27498421/175318727-8bc7a2d3-4e18-41a4-9e3b-4502fb0a2e96.png">

- Press any key. The syntax highlighting will return to normal.
<img width="96" alt="image" src="https://user-images.githubusercontent.com/27498421/175318840-239d1811-8b07-48d7-a3a3-7baf68390ab4.png">

### Code snippet

```zsh
antigen bundle zdharma-continuum/fast-syntax-highlighting
```
(this issue also occurs when the plugin is installed through other means)

### Aditional information

This will only impact the token being tab-completed. For example, `cat some_fi[TAB]` will highlight `cat` correctly, but display `some_file` in white. 

### Self-service

- [ ] I'd be willing to address this documentation request myself.

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/z-shell/community/blob/main/docs/CONTRIBUTING_GUIDELINES.md).

### Are you familiar with Contributor Covenant Code of Conduct?

- [X] I have read the [Contributor Covenant Code of Conduct](https://github.com/z-shell/zi/blob/main/docs/CODE_OF_CONDUCT.md).

**Comment by ss-o** [comment]
antigen bundle zdharma-continuum/fast-syntax-highlighting

From the above, it seems that you opened an issue at the wrong repository.
