### ISSUE TITLE
git command: chroma/-git.ch: function definition file not found

### ISSUE THREAD

**Issue by arsham** [zdharma/fast-syntax-highlighting#21]
With the latest update, by invoking `git` command I get:
```bash
-fast-highlight-process:220: chroma/-git.ch: function definition file not found
```

OS: `Arch Linux`
git version: `2.17.1`

**Comment by psprint** [comment]
could you send me result of `ls -R` in plugin's directory?

**Comment by arsham** [comment]
Here you go:
```bash
.:
chroma/  images/  test/  themes/  fast-highlight  fast-read-ini-file  fast-syntax-highlighting.plugin.zsh  _fast-theme  fast-theme  LICENSE  README.md

./chroma:
-git.ch

./images:
array-assign.png  assign.png  cmdsubst.png  cplx_cond.png  eval_cmp.png  execfd_cmp.png  execfd.png  for-loop.png  function.png  herestring.png  in_string.png  math.gif  parameter.png  theme.png  typeset.png  zcalc.png

./test:
parse.zsh*  to-parse.zsh

./themes:
clean.ini  default.ini  forest.ini  free.ini  safari.ini  zdharma.ini
```

**Comment by arsham** [comment]
Antibody.

**Comment by psprint** [comment]
Can you show `print -rl -- ${fpath[@]}` ?

**Comment by arsham** [comment]
```bash
/home/arsham/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh/functions
/home/arsham/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh/completions
/home/arsham/dotfiles/completions
/home/arsham/dotfiles/functions
/usr/local/share/zsh/site-functions
/usr/share/zsh/site-functions
/usr/share/zsh/functions/Calendar
/usr/share/zsh/functions/Chpwd
/usr/share/zsh/functions/Completion
/usr/share/zsh/functions/Completion/Base
/usr/share/zsh/functions/Completion/Linux
/usr/share/zsh/functions/Completion/Unix
/usr/share/zsh/functions/Completion/X
/usr/share/zsh/functions/Completion/Zsh
/usr/share/zsh/functions/Exceptions
/usr/share/zsh/functions/Math
/usr/share/zsh/functions/MIME
/usr/share/zsh/functions/Misc
/usr/share/zsh/functions/Newuser
/usr/share/zsh/functions/Prompts
/usr/share/zsh/functions/TCP
/usr/share/zsh/functions/VCS_Info
/usr/share/zsh/functions/VCS_Info/Backends
/usr/share/zsh/functions/Zftp
/usr/share/zsh/functions/Zle
/home/arsham/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-completions/src
```

**Comment by psprint** [comment]
Antibody doesn't extend `$fpath`, I don't know why. I will try to reach author and ask, and test antibody myself, maybe prepare a patch. You can fix the problem by adding FSH's directory into `$fpath` somewhere in `zshrc`:

```zsh
fpath+=( /home/arsham/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zdharma-SLASH-fast-syntax-highlighting )
```

I'm not sure if the path is correct, you can verify with your filesystem.

That said, `zsh-users/zsh-completions` has its directory in `$fpath`, I wonder why FSH is treated differently.

**Comment by psprint** [comment]
PS. Git is now specially colorized, currently only subcommand `push` – proper remote and branch is highlighted.

**Comment by arsham** [comment]
That temporary fix works. Let's see how antobody's author responds.
Cheers.

**Comment by psprint** [comment]
Great

**Comment by psprint** [comment]
Antibody author responded quickly with a fix, does FSH work normally with new Antibody?

**Comment by arsham** [comment]
It's not merged yet. I will try it and will let you know. Thanks for the super fast response.

**Comment by psprint** [comment]
n/p, thanks

**Comment by eikenb** [comment]
I am also getting this error. I don't use a plugin manager, just source it from my .zshrc. Noting your fpath change to fix it with antibody I tried a similar fix (adding the cloned repo dir to fpath) and it seemed to fix it. 

    source $ZDOTDIR/upstream/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
    fpath+=($ZDOTDIR/upstream/fast-syntax-highlighting)

Maybe you could add a note about extending the fpath to the standalone installation section of the README.

**Comment by arsham** [comment]
It is fixed. Thanks!

**Comment by psprint** [comment]
> Maybe you could add a note about extending the fpath to the standalone installation section of the README.

I've updated the plugin so that it handles fpath itself, *if needed*. I normally do this in my plugins, to allow plain sourcing, forgot about it now.

Glad that Antibody case is resolved.
