### ISSUE TITLE
Strings starting with "#" are invisible

### ISSUE THREAD

**Issue by khughitt** [zdharma/fast-syntax-highlighting#217]
Greetings!

I am encountering an issue where any strings starting with "#" are invisible in my terminal, due to a similar background/foreground being used.

Moreover, the hexadecimal color support does not appear to work, so even typing something like "#fff" or "#ff00ee" has no effect.

Switching to a different terminal color theme improves the situation slightly, although for each theme tested, the contrast is very low (dark foreground/background colors used).

Any ideas what the issue could be?

**System info**:

- Arch Linux
- Zsh 5.8
- zinit (commit #4457b998cd1d22478f78f2d876a75ae98eda3e94 dec 29, 2020)
- fast-syntax-highlighting (commit #a62d721affc771de2c78201d868d80668a84c1e1 jan 21, 2021)
- kitty 0.19.3
- `TERM=xterm-kitty`

terminal colors:

```
foreground      #abb2bf
background      #282c34

# black
color0  #282c34
color8  #5c6370

# red
color1  #e06c75
color9  #be5046

# green
color2  #98c379
color10 #7a9f60

# yellow
color3  #e5c07b
color11 #d19a66

# blue
color4  #61afef
color12 #3b84c0

# magenta
color5  #c678dd
color13 #9a52af

# cyan
color6  #56b6c2
color14 #3c909b

# white
color7  #abb2bf
color15 #828997
```

**Comment by vincentqb** [comment]
I fixed the issue of invisible comments by changing the theme selected for fast-syntax-highlighting. In particular, I added `fast-theme q-jmnemonic &> /dev/null` to my `.zshrc`. As suggested [here](https://github.com/zsh-users/zsh-syntax-highlighting/issues/510#issuecomment-376772299), the terminal colors are probably out of tune.

**Comment by khughitt** [comment]
Thanks for the suggestion, @vincentqb ! That did the trick! I had tried a couple of the other themes before, but they had similar issues. `q-jmnemonic` is working great though. 

Going to close this issue since it seems likely to just be situations/dependent on the users underlying color configuration, and not much fast-syntax-highlighting can do to avoid that. Feel free to re-open though if I'm mistaken and there is a way to try and check for / avoid this kind of thing.
