### ISSUE TITLE
zfsh makes typing a path on a slow drive horribly slow

### ISSUE THREAD

**Issue by Arkanosis** [zdharma/fast-syntax-highlighting#22]
I have a NFS directory called `/net` which is very slow. If I type `/net/`, any subsequent character (apart from backspace) takes a horribly long time to appear (to the point I initially thought zfsh was preventing me from typing at all). Maybe adding some timeout somewhere may improve this?

Thanks!

**Comment by psprint** [comment]
Adding the following to zshrc:

```zsh
FAST_BLIST_PATTERNS[/net*]=1
```

Should help, does it work?

**Comment by psprint** [comment]
That is a puzzle, it should stop highlighting paths under `/net*`. Can you verify that it stops highlighting those paths even though it is still slow?

**Comment by Arkanosis** [comment]
> Can you verify that it stops highlighting those paths

No, it's still highlighting them.

Note that I'm using zfsh [by sourcing the plugin](https://github.com/Arkanosis/Arkonf/blob/aeb702086bfd9917e6117c6644aab5c954be28c5/zsh/.zsh/zshrc#L51) in my zshrc (just in case it is of any relevance).

**Comment by psprint** [comment]
Ok I have identified the problem, thanks. I will fix this in few upcoming days.

**Comment by Arkanosis** [comment]
Thanks Sebastian. Unfortunately, it still behaves the same way (still slow, still trying to highlight)… :-/

(OT: it looks like zdharma.org is offline)

**Comment by psprint** [comment]
To use async path checking it is now needed to assign `FAST_HIGHLIGH[use_async]=1` before or after loading the plugin.

**Comment by psprint** [comment]
> Thanks Sebastian. Unfortunately, it still behaves the same way (still slow, still trying to highlight)… :-/

I just realized: you were probably testing 1st word at command line? I.e. not "command testing-this and-this", but "testing-this-already not-this". Could you confirm? Basically I've missed one place in code where paths are checked.

**Comment by Arkanosis** [comment]
Hi Sebastian,

> I just realized: you were probably testing 1st word at command line?

Yes, exactly. I should have made it clearer, sorry. I've just tested the following:

    $ /net/

… then it hangs, whereas after the following:

    $ ls /net/…

… I can type whatever I want without any slowdown.

I'm currently using the master branch, which I'm loading using the most likely overkill:

    typeset -Ag FAST_BLIST_PATTERNS
    FAST_BLIST_PATTERNS[/net*]=1
    source plugins/fast-syntax-highlighting.plugin.zsh
    FAST_BLIST_PATTERNS[/net*]=1

Using `FAST_HIGHLIGH[use_async]=1` does not seem to change anything in my case.

Thanks!

**Comment by psprint** [comment]
It should be correct now, I've pushed a patch :)

**Comment by psprint** [comment]
Thanks!
