### ISSUE TITLE
Unable to change theme on nixos

### ISSUE THREAD

**Issue by Th0rgal** [zdharma/fast-syntax-highlighting#223]
Hello,

I am a nixos user and I am using zsh with PowerLevel10k. I really like fast-syntax-highlighting but I a not satisfied with the default theme: it doesn't look very well on my desktop. I would like to use the theme called ``spa``. Unfortunately fast-theme doesn't work on nixos because this is a deterministic linux distribution, everything is managed in the nixos configurations and the generated output is read-only. This is what I get when I run ``fast-theme spa``:
![image](https://user-images.githubusercontent.com/41830259/116776922-8a184100-aa6b-11eb-88af-32ff8a14d9a8.png)

It works well in the current session but it will be reset to default when I restart the shell.

Because the theme is installed that way:
```nix
        {
          name = "fast-syntax-highlighting";
          src = pkgs.fetchFromGitHub {
            owner = "zdharma";
            repo = "fast-syntax-highlighting";
            rev = "v1.55";
            sha256 = "0h7f27gz586xxw7cc0wyiv3bx0x3qih2wwh05ad85bh2h834ar8d";
          };
        }
```

I tried to fork the project and replace default.ini by spa.ini within my fork: https://github.com/Th0rgal/fast-syntax-highlighting/tree/master/themes

Unfortunately it seems this is not enough because it keeps the previous "default theme". Do you have any suggestion?

Sincerely,
Thomas

**Comment by SebTM** [comment]
Hey Thomas,

I came random across and had the same problem under NixOS - after checking the code I found a solution that worked for me - maybe it makes it also for you :-)

I added the plugin to `zsh.plugins` (like you did), and found in fast-theme as well as in fast-highlight a variable ($FAST_WORK_DIR 1/2) for the working-directory used (also possible by CLI-parameter -w). So I created a folder in ".zsh/fsh/" and added to `zsh.initExtra`:

`
export FAST_WORK_DIR=$HOME/.zsh/fsh/
`

Now I was able to use `fast-theme` to switch to different themes, I verified that `current_theme.zsh` and `secondary_theme.zsh` got created in ".zsh/fsh/". In the end I restarted the terminal and verified active theme with `fast-theme --show` which was still correct.

Best Regards!

1 https://github.com/zdharma/fast-syntax-highlighting/blob/master/fast-theme#L71
2 https://github.com/zdharma/fast-syntax-highlighting/blob/master/fast-highlight#L50

**Comment by Th0rgal** [comment]
Thank you very much, this worked well! Do you know how we could force the creation of that folder to make sure the configuration keep reproducible?

**Comment by Th0rgal** [comment]
> Hey Thomas,
> 
> I came random across and had the same problem under NixOS - after checking the code I found a solution that worked for me - maybe it makes it also for you :-)
> 
> I added the plugin to `zsh.plugins` (like you did), and found in fast-theme as well as in fast-highlight a variable ($FAST_WORK_DIR 1/2) for the working-directory used (also possible by CLI-parameter -w). So I created a folder in ".zsh/fsh/" and added to `zsh.initExtra`:
> 
> `export FAST_WORK_DIR=$HOME/.zsh/fsh/`
> 
> Now I was able to use `fast-theme` to switch to different themes, I verified that `current_theme.zsh` and `secondary_theme.zsh` got created in ".zsh/fsh/". In the end I restarted the terminal and verified active theme with `fast-theme --show` which was still correct.
> 
> Best Regards!
> 
> 1 https://github.com/zdharma/fast-syntax-highlighting/blob/master/fast-theme#L71
> 2 https://github.com/zdharma/fast-syntax-highlighting/blob/master/fast-highlight#L50

Hmm unfortunately I get a new issue: I can change my theme without problem, but when I start a new terminal, it is not perfectly loaded.
![screenshot](https://media.discordapp.net/attachments/751050549641871492/842474449235607562/unknown.png)

**Comment by SebTM** [comment]
Yeah, you are right, I could reproduce it! I switched the part where I set `$FAST_WORK_DIR` to `zsh.initExtraFirst` to be the first in .zshrc and this resolved the issue for me.

How do you load I guess powerlevel10k-theme your are using?

**Comment by SebTM** [comment]
For the directory there are several solutions:
- You could make an if-statement in your .zshrc checking if the directory exists and if not creating it before you set it
- You can create dummy-files by `xdg.configFile` so it will ensure that the directory exists
- Or if you have https://nix-community.github.io/home-manager/options.html#opt-xdg.userDirs.enable active, you could try hack something with extra-config but it seems the most hacky way

**Comment by Th0rgal** [comment]
Hey @SebTM ! Thank you very much for the answer. Here is what it looks like:
```nix
      initExtraFirst = ''
        [ ! -d "$HOME/.zsh/fsh/" ] && mkdir $HOME/.zsh/fsh/
        export FAST_WORK_DIR=$HOME/.zsh/fsh/;
      '';
```

This works perfectly!
