### ISSUE TITLE
How do we disable chroma?

### ISSUE THREAD

**Issue by kergoth** [zdharma/fast-syntax-highlighting#23]
As the subject line states, there needs to be a way to either disable chroma functions across the board, or disable specific ones. Further, the vim chroma needs the ability to specify the viminfo path. The vim chroma is both completely useless to me and is actually wrong, since my viminfo isn't at ~/.viminfo unless my vimrc has been bypassed.

**Comment by psprint** [comment]
This topic is ongoing, the selective disabling (and enabling) of chroma functions, plus decision about some API to plug-in chroma, or just to forget about it and commit to upstream, single repo has its all. It should resolve for a week, thanks for hint about vim disabling, this helps.

Currently, you can paste this to zshrc after sourcing plugin:

FAST_HIGHLIGHT=(
  chroma-git     chroma/-git.ch
  chroma-example chroma/-example.ch
  chroma-grep    chroma/-grep.ch
  chroma-egrep   chroma/-grep.ch
  chroma-fgrep   chroma/-grep.ch
  chroma-perl    chroma/-perl.ch
  chroma-make    chroma/-make.ch
  chroma-awk     chroma/-awk.ch
  chroma-gawk    chroma/-awk.ch
  chroma-mawk    chroma/-awk.ch
)

I.e. to enumerate existing chromas but skip vim.

**Comment by robobenklein** [comment]
I agree it would be nice to set either a blacklist or a whitelist on the chroma functions. I came here because of a problem with the `which` chroma completely destroying the prompt:

https://asciinema.org/a/Io9LPPphMZGMJDTFslIBTxra5

**Comment by psprint** [comment]
Guys I'm middle of coding spree, the reasonable parts like enabling or displaying chroma will be implemented but currently I extend volume of new features as this is more fun. Hold on 5 days, and tell what isn't OK, I'll fix it.

**Comment by kergoth** [comment]
Fine with me, thanks for the quick response, it's appreciated. I'm just overriding `FAST_HIGHLIGHT` as you suggested for now. These new features are quite interesting, I haven't seen shell syntax highlighting extended in this way before.

**Comment by TeeSeal** [comment]
Disabling chroma no longer works with `FAST_HIGHLIGHT=()` :(

**Comment by psprint** [comment]
Is it put after loading of plugin? Then it will work. I'm currently coding, created 3 new branches, much is coming into fast-syntax-highlighting, but feeling little guilty that I left you with preliminary chroma (but there are successful chromas, like `-git.ch`). Disabling a particular chroma means commenting it out in following code, executed after loading plugin:

```zsh
FAST_HIGHLIGHT+=(
  chroma-grep    chroma/-grep.ch   # Triple
  chroma-egrep   chroma/-grep.ch
  chroma-fgrep   chroma/-grep.ch
  chroma-awk     chroma/-awk.ch    # Triple
  chroma-gawk    chroma/-awk.ch
  chroma-mawk    chroma/-awk.ch
  chroma-source  chroma/-source.ch # Double
  chroma-.       chroma/-source.ch
  chroma-sh      chroma/-sh.ch     # Five targets
  chroma-zsh     chroma/-sh.ch
  chroma-bash    chroma/-sh.ch
  chroma-fish    chroma/-sh.ch
  chroma-tmux    chroma/-sh.ch
  #chroma-vim     chroma/-vim.ch
  chroma-make    chroma/-make.ch
  chroma-perl    chroma/-perl.ch
  chroma-git     chroma/-git.ch
  chroma-example chroma/-example.ch
  chroma-docker  chroma/-docker.ch
  chroma-autoload chroma/-autoload.ch
  chroma-ssh     chroma/-ssh.ch
  chroma-scp     chroma/-scp.ch
  #chroma-which   chroma/-which.ch
  chroma-printf  chroma/-printf.ch
  chroma-ruby    chroma/-ruby.ch
)

I've already commented out the most experimental chromas (`vim` and `which`).
```

**Comment by Adaephon-GH** [comment]
You can also disable specific chromas by unsetting them in `FAST_HIGHLIGHT` after fast-syntax-highlighting has been loaded. For example

    unset "FAST_HIGHLIGHT[chroma-vim]"
    unset "FAST_HIGHLIGTH[chroma-git]"

would deactivate the vim and git chromas while keeping all others.

This way you will not have to maintain a full copy of the list of available chromas.

**Comment by psprint** [comment]
@Adaephon-GH: Thanks, this is much better than 1 or 2 pages long code.

**Comment by psprint** [comment]
What are objections for chromas? I'm currently extending them, I'm positive for them, [they allow detailed highlighting](https://asciinema.org/a/194534), the initial problems are solved, should I allow to disable chroma using some supported method?
