### ISSUE TITLE
-make.ch chroma is broken

### ISSUE THREAD

**Issue by JumperPunk** [zdharma/fast-syntax-highlighting#24]
If the file "Makefile" does not exist in the current directory, this is shown:
chroma/-make.ch:46: no such file or directory: Makefile

If "Makefile" does exist, then this is shown:
chroma/-make.ch:46: -fast-make-targets: function definition file not found

It should also be noted that "makefile" (lowercase) is also expected by `make`.

**Comment by psprint** [comment]
Great. With any problem, don't hesitate to open issue. Thanks
