### ISSUE TITLE
The git commit message limit should be 50 (or configurable)

### ISSUE THREAD

**Issue by agross** [zdharma/fast-syntax-highlighting#25]
GitHub web suggest this, Visual Studio Code turns the line red at 50 chars. If you do not want to change the currently hard-coded 72, please make it configurable.

https://stackoverflow.com/a/11993051/149264

**Comment by plexigras** [comment]
making it `incorrect-subtle` instead of `unknown-token`

https://github.com/zdharma/fast-syntax-highlighting/blob/c599449ea46bd23b2095b43fca76f6d3443449bc/chroma/-git.ch#L90

**Comment by psprint** [comment]
I've changed this a while ago, it uses `50` characters limit now
