### ISSUE TITLE
Wired output with "which"

### ISSUE THREAD

**Issue by arsham** [zdharma/fast-syntax-highlighting#29]
When using `which` command, with entering any characters after the first space, or with the following line:
```bash
$ ls -l $(which blush)
```
When the last parentheses is pressed it shows the following:
```bash
command which: /home/arsham/Projects/Go/bin/blush
builtin which: /home/arsham/Projects/Go/bin/blush
type -w: blush: command
whence -v: blush is /home/arsham/Projects/Go/bin/blush
whereis: blush: /home/arsham/Projects/Go/bin/blush
whatis: 
```
And doesn't produce any output. I can confirm the snippet works when this plugin is not used.
It also appears when using the arrow keys to browse the history.

OS: Linux
Zsh: 5.5.1-1
Plugin manager: antibody 
fast-syntax-highlighting head: 523d6970

**Comment by psprint** [comment]
I turned off `which` chroma, it should be ok now.

**Comment by arsham** [comment]
Thank you, it is fixed now.
