### ISSUE TITLE
Terminal closing after paste medium string, Ctrl+C don't work

### ISSUE THREAD

**Issue by popstas** [zdharma/fast-syntax-highlighting#30]
Example string: `openssl req -new -newkey rsa:4096 > registry.csr`:

```
$ openssl req -new -newkey rsa:4096 > regisrealloc(): invalid old size
Connection to localhost closed.
```

Tried to reduce string, with paste of `openssl req -new -newkey rsa:4096 > regis` or less terminal don't closing, but don't work Ctrl+C hotkey and command don't colorized before I delete or add one symbol.

This bug appears after fix of #26.

**Comment by psprint** [comment]
On 17 June 2018 at 15:05, Stanislav Popov <notifications@github.com> wrote:

> Example string: openssl req -new -newkey rsa:4096 > registry.csr:
>
> $ openssl req -new -newkey rsa:4096 > regisrealloc(): invalid old size
> Connection to localhost closed.
>
> Tried to reduce string, with paste of openssl req -new -newkey rsa:4096 >
> regis or less terminal don't closing, but don't work Ctrl+C hotkey and
> command don't colorized before I delete or add one symbol.
>
> This bug appears after fix of #26
> <https://github.com/zdharma/fast-syntax-highlighting/issues/26>.
>

So if you `git checkout v1.21`, i.e. checkout an older version of FSH, the
bug doesn't occur? It looks like a segfault, bug with realloc() function.
Could you create docker image where this reproduces? I've tried pasting the
string bug nothing happens.

I assume you did `zsh`, then `zsh`, then paste, to be able to see segfault
message (it's probably the "realloc(): invalid old size"). If not then you
could try, more could be printing. That sait, logging to remote session
seems to work the same.

-- 
Best regards,
Sebastian Gniazdowski

**Comment by psprint** [comment]
Which Zsh version?

**Comment by psprint** [comment]
I can confirm Ctrl-C problems, i.e. I cannot reproduce segfault, however after pasting your string, when I first delete some character with Backspace, then I cannot break out of it by pressing Ctrl-C. If I do `FAST_HIGHLIGHT[no_check_paths]=1`, which disables path-checking, then no Ctrl-C problem occurs. This suggest an issue with `<(...)` background processes. @ericfreese, I have to ask again, were there such problems with zpty or now with `<()`? I think that there's a bug in Zsh that moves signal handling to `<()` process, so main zsh thread stops responding to them.

**Comment by psprint** [comment]
@popstas: I've finally found workaround for Ctrl-C problems and maybe it also spans on the segfaults you reported. Could you check latest HEAD (tag: v1.22) if the terminal-closing (probably a segfault) still occurs?

**Comment by popstas** [comment]
Same behaviour... Paste of `openssl req -new -newkey rsa:4096 > registry.csr` still crashing terminal.

**Comment by popstas** [comment]
I found breaking commit with git bisect - https://github.com/zdharma/fast-syntax-highlighting/commit/5a6684c6b7335374e93f88e42ba1db8f25ebd7c0

At https://github.com/zdharma/fast-syntax-highlighting/commit/1d7d6f579a18d6ecafc55702168c0ff9f53ea9c7 paste works fine.

**Comment by psprint** [comment]
I've added a commit that makes async-path-checking (good for slow NFS drives, etc.) optional. `FAST_HIGHLIGHT[use_async]=1` is required to enable asynchronous path checking. So FSH should now behave like pre-5a6684c version, by default.

**Comment by popstas** [comment]
Thank you! You fixed problem!
