### ISSUE TITLE
illegal character: ]

### ISSUE THREAD

**Issue by vlle** [zdharma/fast-syntax-highlighting#31]
I get errors when using square brackets:
```
# { ~ }
ζ » echo test]  a
-fast-highlight-process:560: bad math expression: illegal character: ]

# { ~ }
ζ » echo test]  aa

# { ~ }
ζ 130 » echo test[
-fast-highlight-process:560: invalid subscript

# { ~ }
ζ 130 » echo test[  a
-fast-highlight-process:560: invalid subscript

```
And when using arrow up to go through history it gives the error again, making it impossible to go up in history (works fine after ```exec zsh```, till I type a bracket again).

**Comment by psprint** [comment]
It should be working now, just commited a fix. Thanks for reporting.

**Comment by vlle** [comment]
Thanks, works great!
