### ISSUE TITLE
$HOME/.zgen/zdharma/fast-syntax-highlighting-master/fast-highlight:functions:1133: -M fsh_sy_h_append: function already exists

### ISSUE THREAD

**Issue by esn89** [zdharma/fast-syntax-highlighting#32]
I have been getting this after running an update, any ideas?

**Comment by psprint** [comment]
I cannot see any other explanation than sourcing the plugin twice or more times. I've silenced this warning, however something might do additional loads of the plugin.

**Comment by esn89** [comment]
@psprint 

Thanks a million.
