### ISSUE TITLE
string highlighting gone after latest update

### ISSUE THREAD

**Issue by esn89** [zdharma/fast-syntax-highlighting#33]
Hi, when I used to run a grep command before the update today, it looked like so:

https://imgur.com/0V4up9v

However, after the update of today "zgen update" the grep looks like so:

https://imgur.com/entkGaj

Any ideas why?  Is it a setting I have to enable?

**Comment by psprint** [comment]
It colorizes regex characters now, ones like `+`,` *`, `[]`. But string highlighting should be active too, I'll fix this tomorrow. The general reason is that chroma-functions were introduced, they do detailed or advanced highlighting, e.g. git chroma verifies push remote & branch, `git checkout` verifies if given SHA hash is correct, etc.

**Comment by esn89** [comment]
@psprint 

Any news on this? :)

**Comment by psprint** [comment]
@esn89 I've commited a patch, it should be correct now

**Comment by esn89** [comment]
thanks man!
