### ISSUE TITLE
Docs about how to apply this to stdin

### ISSUE THREAD

**Issue by SerialVelocity** [zdharma/fast-syntax-highlighting#34]
Would be nice if you could document how to run this over arbitrary strings. I'm assuming it is something like the following:
```
$ echo 'echo "Hi"' | zsh-highlight
```

I can't find the right function to call though!

**Comment by psprint** [comment]
This requires a new feature. The highlighting that is done is based on `region_highlight` Zsh array. You put there `region_highlight+=( "1 10 fg=blue")` to have 10 characters, from position 1 to position 10, colored in blue. So currently there is no mechanism that would print `echo "Hi"` with terminal escape codes. Can I ask for what purpose do you need this?

**Comment by SerialVelocity** [comment]
I'm using [fzf](https://github.com/junegunn/fzf) preview to look through my history. The default view only highlights the text I'm searching for (as I want), but I want the preview window to have syntax highlighting. I enable the preview window because most of my lines are larger than my terminal width.

I find this plugin has much nicer syntax highlighting than other things like rouge, pygments, etc as they are built to highlight script files, not single lines.

My setup is:
```
local fzf_base=$(brew --prefix)/opt/fzf
source "${fzf_base}/shell/key-bindings.zsh"
export FZF_CTRL_R_OPTS="--preview 'echo {} | cut -d\" \" -f2- | fold -w $(($(tput cols)-4))' --preview-window down:4"
```

**Comment by psprint** [comment]
I could start a new project and implement this, but it is somewhat demanding to extract current highlihter, so I can do it for a $15 donation. I have a [PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=H4GZAACT2MQ3W) button.

**Comment by psprint** [comment]
Fzf starts a new process and FSH can highlight better than other tools because it runs within current shell. So this feature is rather impossible.

**Comment by JayXon** [comment]
Ctrl-R with `fzf` uses the output of `fc -rl 1` which is a shell built-in command, is it possible to apply syntax highlighting to `fc` or write a function that outputs syntax highlighted version of `fc -rl 1`?
Basically I want history-search-multi-word but with fuzzy search.

**Comment by psprint** [comment]
@JayXon: That's a very interesting idea! I'm looking at it now!

**Comment by psprint** [comment]
Sadly this turns out again to be impossible – the output of `fc 1` is long, and FSH can quickly colorize say 100 lines of text. So it cannot be applied to the whole input data, but only on the data to be currently displayed.

**Comment by JayXon** [comment]
How slow are we talking here? `fzf` can start displaying result before all the input is generated and update the result in real time as it comes in.
So if we can colorize the last 100 lines of history right away it should cover most cases.

**Comment by psprint** [comment]
Hmm, that's an interesting point of view. I must kinda guess right now, as I don't have time to check – it seems that the `n-history` function is colorized in about 1.5 seconds, and it has 300 lines, so the pace is around 200 lines / second of output. That's kinda slow.

**Comment by BirkhoffLee** [comment]
@psprint if this get implemented it would be so great for fzf users - is there any other workarounds that might work for the current version?
