### ISSUE TITLE
Chroma functions and aliased commands

### ISSUE THREAD

**Issue by looselyrigorous** [zdharma/fast-syntax-highlighting#36]
I'm using OMZ-style git aliases and I noticed that when I do `gcm "...72chars"` the chroma
function does not apply for the commit message.

Is it feasible to make the chroma functions resolve aliased commands?

**Comment by psprint** [comment]
Yes that's doable, rather not difficult, right now you can enable the chroma for `gcm` by doing:

```zsh
FAST_HIGHLIGHT+=( "chroma-gcm" "chroma/-git.ch" )
```
I will implement general alias support soon.

**Comment by psprint** [comment]
I've realized that what I wrote isn't true. A special support was needed, and it was added in https://github.com/zdharma/fast-syntax-highlighting/commit/19a8a5e8c4a53fa73277996b8a0b124847e48946. Aliases are now handled automatically.
