### ISSUE TITLE
Errors on math function use to check command existence.

### ISSUE THREAD

**Issue by robobenklein** [zdharma/fast-syntax-highlighting#38]
Demonstration:

https://asciinema.org/a/ISqk9lDgZvZnEbzIi8p4H4ZxR

`-fast-highlight-math-string:17: invalid subscript `

Reproduction: Try editing this on the command line to check for a different command:

```
(( ${+commands[rtab]} )) && echo yes || echo no
```

**Comment by psprint** [comment]
It should be handled now, thanks

**Comment by psprint** [comment]
Switched to a faster method that also solves the problem

**Comment by robobenklein** [comment]
Confirmed fix works! Thanks
