### ISSUE TITLE
Not working as expected in CentOS 6.9

### ISSUE THREAD

**Issue by zhengweidi** [zdharma/fast-syntax-highlighting#39]
The following error message will appear when you enter any character after any command.
```
-fast-highlight-process:562: bad option: -w
```

like this
<img width="376" alt="image" src="https://user-images.githubusercontent.com/31889177/42196105-b35b34e6-7eae-11e8-9dfe-95288c797e5c.png">

**Comment by psprint** [comment]
Which Zsh version? (echo $ZSH_VERSION)

**Comment by zhengweidi** [comment]
my zsh version: 4.3.11

**Comment by psprint** [comment]
Error should disappear now, although path checking will not work. I'm looking for full fix now

**Comment by kmonsoor** [comment]
having same issue on `Ubuntu 14.04.3 LTS`, `$ZSH_VERSION` => `5.0.2`

**Comment by psprint** [comment]
Changed range of Zsh versions the fix applies to, it should be OK now.

**Comment by zhengweidi** [comment]
it works now.
