### ISSUE TITLE
Parent directories (.., ../..) colored red in command position

### ISSUE THREAD

**Issue by strindberg** [zdharma/fast-syntax-highlighting#4]
This might be a special case of issue #2, but I notice, even after the fix for that issues, that putting '..' (without quotes of course) on the beginning of the command line makes the dots red. Same with parents further up, such as '../..'.

**Comment by psprint** [comment]
For me the dots are magenta, maybe they just appeared as red, and closer look will confirm? Default config uses magenta for paths, I didn't like underline that is hard to see, at least on iTerm2

**Comment by mgild** [comment]
This works fine for me too.  Likely it's your colorscheme.

**Comment by strindberg** [comment]
Ah, yes. Sorry for the noice: I must have had something malconfigured while experimenting. This works as intended.
