### ISSUE TITLE
Highlight global aliases created by `alias -g`

### ISSUE THREAD

**Issue by HaleTom** [zdharma/fast-syntax-highlighting#41]
Highlight global aliases, created by `alias -g`

I've had cases where supposed literals on the command line (eg a file name) clashed with a global alias (eg after an expansion), and it's quite a head scratcher working out what's going on.

**Comment by HaleTom** [comment]
I'm looking into this at: https://github.com/zsh-users/zsh-syntax-highlighting/issues/265

**Comment by psprint** [comment]
Could a $3 donation be granted for this? I would sit to this today, it would be for a coffee, I would for sure finish today. I have a patreon profile https://www.patreon.com/psprint and a [PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=H4GZAACT2MQ3W) button.

**Comment by psprint** [comment]
I've coded this:

![global-alias](https://user-images.githubusercontent.com/6049288/43560534-40d2ad10-9613-11e8-90ea-0005d8536ec6.png)

After update re-run of `fast-theme` is needed.
