### ISSUE TITLE
Configure / customise colours

### ISSUE THREAD

**Issue by HaleTom** [zdharma/fast-syntax-highlighting#42]
As I understand it, this plugin is based on `zsh-syntax-highlighting`.

Is there a way to configure or customise colours after applying a theme?

Eg, I'd like to be able to do something like:

```
ZSH_HIGHLIGHT_STYLES[alias]='fg=magenta,bold'
```

**Comment by HaleTom** [comment]
I just saw #7 but the example given there did not work for me.

I have:

typeset -A FAST_HIGHLIGHT_STYLES
FAST_HIGHLIGHT_STYLES[unknown-token]="fg=red"
FAST_HIGHLIGHT_STYLES[alias]='fg=magenta,bold'
zplugin ice wait"1"
zplugin light zdharma/fast-syntax-highlighting


1. Should the above work?
1. Would you consider putting a link to issue #7 in the README?

**Comment by psprint** [comment]
I must implement overlay support for the theme files, which are easy to edit INI files, i.e. to first load a theme from project's root, then load user's customizing theme from `~/.config/fast-syntax-highlighting/themes/...`, which will overwrite fields of main loaded theme. A temporary solution for you is: a thing changed, keys in FAST_HIGHLIGHT_STYLES are prepended with theme name, i.e.:

```zsh
typeset -A FAST_HIGHLIGHT_STYLES
FAST_HIGHLIGHT_STYLES[safariunknown-token]="fg=red"
FAST_HIGHLIGHT_STYLES[safarialias]='fg=magenta,bold'
zplugin ice wait"1"
zplugin light zdharma/fast-syntax-highlighting
```

If the customization will be applied after plugin is loaded, there will be `$FAST_THEME_NAME` scalar variable, holding current theme name, so you can do:

```zsh
zplugin ice wait"1"
zplugin light zdharma/fast-syntax-highlighting
FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}unknown-token]="fg=red"
FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}alias]='fg=magenta,bold'
```

**Comment by HaleTom** [comment]
I needed to add:
```
FAST_THEME_NAME=free  # from `fast-theme -l`
```
because it seems that this variable is set only 1 second after `zsh` loads given the `ice wait"1"`.

**Comment by psprint** [comment]
Does lack of `$FAST_THEME_NAME` still occur? I remember I have had a lack of it when testing at time of this thread, now it is available but I think it happened once today that it was not defined.

**Comment by HaleTom** [comment]
I'm not sure. I explicitly set it so that I run `fast-theme <name>` only when needed:
```
FAST_THEME_NAME=free  # From `fast-theme -l`. `fast-theme -t <theme>` to test
zplugin ice wait'0' atload"[[ current_theme.zsh -nt themes/$FAST_THEME_NAME.ini ]] || fast-theme $FAST_THEME_NAME > /dev/null"
zplugin light 'zdharma/fast-syntax-highlighting'
```

**Comment by psprint** [comment]
Fast-Syntax-Highlighting has been extended with full user-theme support. [README provides information](https://github.com/zdharma/fast-syntax-highlighting#customization) of how to customize F-Sy-H colors, information in this thread is outdated.
