### ISSUE TITLE
Consider importing highlighters: `brackets`, `pattern`, `regexp`

### ISSUE THREAD

**Issue by HaleTom** [zdharma/fast-syntax-highlighting#43]
zsh-syntax-highlight has [these](https://github.com/zsh-users/zsh-syntax-highlighting/tree/master/docs/highlighters) syntax highlighters.

Of those, the ones I see mostly commonly in example config files are:

* `brackets` [(documentation)](
https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/brackets.md)
* `pattern`  [(documentation)](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/pattern.md)
* `regexp`  [(documentation)](
https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/regexp.md)

I find `brackets` the most useful for highlighting unmatched brackets, and highlighting a matching bracket.

Would you consider merging these in?

**Comment by psprint** [comment]
I looked at the code. I must say I wouldn't want to commit it to my project. I can write brackets highlighter so that it handles quoting, so e.g. if you write:

```
prompt# while ( grep ")" ); do echo yes; done
```
Then the two outer brackets will be highlighted, the inner one will be skipped. Any quoting can be supported:

```
prompt# while ( grep \) ); do echo yes; done
```

This will also work. I'm certain because I once did such code, it's simple and easy to understand, no possible flaws in it. But could a donation be granted for this? Like $5? I have a [PayPal button](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=H4GZAACT2MQ3W).

**Comment by psprint** [comment]
Coded this without donation. To enable: `FAST_HIGHLIGHT[use_brackets]=1`. It is without quoting-flaws like I've described.

**Comment by jenniges** [comment]
When I enable this feature with `FAST_HIGHLIGHT[use_brackets]=1`, I get the following error after typing the first character of a new zsh-session.
```
_zsh_highlight:29: array parameter _ZSH_HIGHLIGHT_MAIN_CACHE created globally in function _zsh_highlight
```

**Comment by psprint** [comment]
Fixed this, thanks

**Comment by HaleTom** [comment]
Champion, thank you!

I did indeed check out your donate button.

Why isn't this glory enabled by default and an option to disable it instead?  Who wouldn't want this?

**Comment by psprint** [comment]
Thanks :) It's just that I need to add "[[" skipping. I.e., in main highlighter, remember "[[", "]]", "((", "))", "$((", etc. position and skip brackets contained in it in brackets-highlighter.

**Comment by psprint** [comment]
BTW. I've quite explained the method in reddit post, in comment: https://www.reddit.com/r/zsh/comments/931w99/ideal_highlighting_of_brackets_pairing_etc_in/

**Comment by psprint** [comment]
@HaleTom It's supported, it's little problematic as it was noted in your thread (https://github.com/zdharma/fast-syntax-highlighting/issues/42), but the names of styles are: `bracket-level-1` ... `bracket-level-3`, fixed number of styles. I can increase the number if it's reasonable.

It's normally taken from themes, I should do something about user themes: https://github.com/zdharma/fast-syntax-highlighting/blob/776b12d8ab64e270fd744f42281e3236761bf69d/themes/free.ini#L30-L37

**Comment by psprint** [comment]
**DONE A TASK**: Normal highlighting and brackets-highlighting now cooperate, and are both active by default (no need for `FAST_HIGHLIGHT[use_brackets]=1`). The cooperation means that "[[" and "]]" in "if [[ .... ]]; ..." aren't examined by brackets highlighter, but by main highlighter. The same for "$((...))", "((...))".

**Comment by HaleTom** [comment]
I've tried adding the following:

```
FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}paired-bracket]='bg:blue'
FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}bracket-level-1]='green,bold'
FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}bracket-level-2]='yellow,bold'
FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}bracket-level-3]='cyan,bold'
```

But it seems to break the highlighting. How should it look?

**Comment by psprint** [comment]
Ini files do not require `fg=`, etc. prefixes before style names, but direct assign to `FAST_HIGHLIGHT_STYLES` do require it. Here is what works, together with hint how to do it when using zplugin:

```zsh
zplugin ice wait"1" atload"set_fast_theme"
zplugin light zdharma/fast-syntax-highlighting

set_fast_theme() {
    FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}paired-bracket]='bg=blue'
    FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}bracket-level-1]='fg=red,bold'
    FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}bracket-level-2]='fg=magenta,bold'
    FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}bracket-level-3]='fg=cyan,bold'
}
```

**Comment by HaleTom** [comment]
With this config:

```
FAST_THEME_NAME=free  # From `fast-theme -l`. `fast-theme -t <theme>` to test
zplugin ice wait'0' atload"[[ current_theme.zsh -nt themes/$FAST_THEME_NAME.ini ]] || fast-theme $FAST_THEME_NAME > /dev/null"  # atinit"zpcompinit; zpcdreplay"
zplugin light 'zdharma/fast-syntax-highlighting'
typeset -gA FAST_HIGHLIGHT_STYLES FAST_HIGHLIGHT
FAST_HIGHLIGHT[use_brackets]=1
FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}unknown-token]="fg=green,bold"
FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}paired-bracket]='bg:green'
FAST_HIGHLIGHT_STYLES[${FAST_THEME_NAME}bracket-level-1]='fg=red,bold'
``` 

Any reason that the `unknown-token` style is applied correctly but the brackets aren't?

**Comment by psprint** [comment]
@HaleTom PS. the "bg:blue" should be "bg=blue".

**Comment by psprint** [comment]
@HaleTom I've implemented full support for user-themes. Basically, `fast-theme` obtains a path, e.g. `fast-theme ~/custom.ini`. If the name is special "overlay", it then is applied on top of main-theme and can contain only a few keys. More description is at https://github.com/zdharma/fast-syntax-highlighting/issues/49. I will update README.md tomorrow.
