### ISSUE TITLE
-fast-highlight-process: chroma/-source.ch: function definition file not found

### ISSUE THREAD

**Issue by Scriptim** [zdharma/fast-syntax-highlighting#44]
I frequently get these errors
```
-fast-highlight-process:219: chroma/-source.ch: function definition file not found
-fast-highlight-process:222: chroma/-source.ch: function definition file not found
```
(The two errors do not always occur together)

I couldn't find out exactly when these errors occur, but the first one always occurs when I type `.` (for the working directory). I assume it has to do with file paths.

I have installed `r283.4500583-1` (from the [AUR](https://aur.archlinux.org/packages/zsh-fast-syntax-highlighting-git/) on Arch Linux) and believe the problem only exists since this version.

**Comment by psprint** [comment]
I've commited a fix that will allow normal fallback operation when a chroma isn't found. To investigate more, could you paste contents of `{fsh-directory}/chroma` dir?

**Comment by Scriptim** [comment]
Strangely enough, I only had two files in `/usr/share/zsh/plugins/fast-syntax-highlighting/`, namely `fast-highlight` and `fast-syntax-highlighting.plugin.zsh`. There was no `chroma` directory at all. Now I just installed your fix and the directory has been extended by some files, including the `chroma` directory that matches [/tree/master/chroma](https://github.com/zdharma/fast-syntax-highlighting/tree/master/chroma).

Anyway, the problem no longer occurs, so thank you.
