### ISSUE TITLE
wrong alias chroma start position

### ISSUE THREAD

**Issue by plexigras** [zdharma/fast-syntax-highlighting#46]
if i type `gc a` i get `git -100000 2`, `commit -100000 2`, `a 1 2` where it should be `a 3 4`

**Comment by plexigras** [comment]
to clarify if i type `git commit a` i get `git 0 3`, `commit 4 10` and `a 11 12`

and if type `cd a` i get `cd 0 2` and `a 3 4`

**Comment by psprint** [comment]
I've tested this, and for me [it returns "3 4" (asciinema)](https://asciinema.org/a/IIjaVqpd7aBMHMnVwF8Z6jUFx)
![fsh-chroma-alias](https://user-images.githubusercontent.com/6049288/43070684-cb22079a-8e70-11e8-849e-e50ad0d8f5b1.png)
, weird.

**Comment by plexigras** [comment]
if i return 1 in a chroma in normally don't have to set `this_word` and `_start_pos` but for aliases i do

**Comment by plexigras** [comment]
a temporary workaround is to do

```
if [[ $3 < 0 ]]; then
    (( this_word = next_word ))
    _start_pos=$4
    return 0
else
    return 1
fi
```
