### ISSUE TITLE
Plugin fails to load on zsh version 5.0.7

### ISSUE THREAD

**Issue by jonbarksdale** [zdharma/fast-syntax-highlighting#48]
Just updated today, and when I start a new shell I get this:
```
[zplug] These repos have failed to load:
- zdharma/fast-syntax-highlighting
```
and any typing spits out these: 
```
_zsh_highlight:26: command not found: -fast-highlight-init
_zsh_highlight:27: command not found: -fast-highlight-process
_zsh_highlight:26: command not found: -fast-highlight-init
_zsh_highlight:27: command not found: -fast-highlight-process
```

From what I can tell using the wonders of git bisect, this is the commit that broke things:
```
commit b33a5fd6e9045d948bd100e2a08adae167212dd4
Author: Sebastian Gniazdowski <sgniazdowski@gmail.com>
Date:   Mon Jul 30 08:22:09 2018 +0200

    fast-theme: Support 4 new styles (for brackets)

    Issue #43
```

I've been able to trace it down to line 275 in fast-syntax-highlighting.plugin.zsh, and it looks like the older syntax doesn't allow for () syntax to create associative arrays? 

This change seems to fix it.
```
diff --git a/fast-syntax-highlighting.plugin.zsh b/fast-syntax-highlighting.plugin.zsh
index f597cba..0d27e1b 100644
--- a/fast-syntax-highlighting.plugin.zsh
+++ b/fast-syntax-highlighting.plugin.zsh
@@ -275,7 +275,7 @@ _zsh_highlight_preexec_hook()
 {
   typeset -g _ZSH_HIGHLIGHT_PRIOR_BUFFER=
   typeset -gi _ZSH_HIGHLIGHT_PRIOR_CURSOR=0
-  typeset -ga _ZSH_HIGHLIGHT_MAIN_CACHE=()
+  typeset -gA _ZSH_HIGHLIGHT_MAIN_CACHE
 }

 autoload -Uz add-zsh-hook
```

**Comment by psprint** [comment]
Really thanks, I've did a mistake, only new Zsh support initializing array at defining it.

**Comment by jonbarksdale** [comment]
It does! Thanks for getting that fix out so quickly :)

**Comment by jonbarksdale** [comment]
Also, I 'm not 100% sure why the old code didn't work, I scoured the zsh release notes and nothing really addressed it.  If you figure it out, please share, I'm curious what changed between 5.0.7 and newer versions.

**Comment by BonaBeavis** [comment]
Since this commit I have a similar error: [plugin.zsh: Fix bug with ZERO param leakage and follow Zsh Plugin Std. · zdharma/fast-syntax-highlighting@efee0e2](https://github.com/zdharma/fast-syntax-highlighting/commit/efee0e2560e2b8c40c278acbb5f8cc67985cef84).
It can load fsh, but throws:
```
_zsh_highlight:26: command not found: -fast-highlight-init
_zsh_highlight:27: command not found: -fast-highlight-process
```
On start and every input. Zsh version is 5.5.1.

**Comment by psprint** [comment]
@BonaBeavis: That's really weird. To track this, I've prepared a debugging-equipped version of main F-Sy-H source file. Could you apply it and send me copy of the output on terminal from F-Sy-H at the loading moment? 

The debug-code Is available as:

1. A whole file that should be copied onto `{fsyh-location}/fast-syntax-highlighting.plugin.zsh`
2. A patch `fsh-problem.diff` that should be copied into `{fsyh-location}` and applied by: `patch -p1 -i fsh-problem.diff`

So basically you can choose the method of adding debug-code into your F-Sy-H installation – only one from the two items should be done. The files are attached to this post, with additional `.txt` extension:

[fast-syntax-highlighting.plugin.zsh.txt](https://github.com/zdharma/fast-syntax-highlighting/files/2601734/fast-syntax-highlighting.plugin.zsh.txt)
[fsh-problem.diff.txt](https://github.com/zdharma/fast-syntax-highlighting/files/2601735/fsh-problem.diff.txt)

or available from my Blinkenshell account:

http://psprint.blinkenshell.org/fast-syntax-highlighting.plugin.zsh
http://psprint.blinkenshell.org/fsh-problem.diff

Could you help?

To find F-Sy-H location on disk, you can use `zplg cd zdharma/fast-syntax-highlighting` in case you're using `zplugin`, or by `echo $FAST_BASE_DIR` – but the debug is to check if `$FAST_BASE_DIR` is broken, so it might not show the correct directory. Nevertheless, entering plugin's manager directory like `cd ~/.zgen` or `cd ~/.zplug` and then running a command:

```zsh
find . -iname '*fast-syntax-highlighting*'
```

should give the F-Sy-H directory where the `fast-syntax-highlighting.plugin.zsh` file exists and where the patch `fsh-problem.diff` should be applied.

**Comment by BonaBeavis** [comment]
Thanks for the detailed instructions, I did a `zplug clear && zplug clean` too. And here is the output:
```
DEBUG: ZSH_VERSION: `5.5.1'
DEBUG1: 0: `/home/beavis/.zplug/repos/zdharma/zsh-diff-so-fancy/zsh-diff-so-fancy.plugin.zsh'
DEBUG1: FAST_BASE_DIR: `/home/beavis/.zplug/repos/zdharma/zsh-diff-so-fancy'
DEBUG2: 0: `/home/beavis/.zplug/repos/zdharma/zsh-diff-so-fancy/zsh-diff-so-fancy.plugin.zsh'
DEBUG2: FAST_BASE_DIR: `/home/beavis/.zplug/repos/zdharma/zsh-diff-so-fancy'
DEBUG3: fast-highlight loading failure
DEBUG3: fast-string-highlight loading failure
```

Additionally I dropped into a new tty terminal and started a clean shell with `zsh -d -f`, the error still persists.

**Comment by psprint** [comment]
It appears that you've pasted output from plugin zsh-diff-so-fancy. What's needed is the output from fast-sy-h. That said, the output looks correct.

**Comment by psprint** [comment]
But wait, it says f-sy-h in last two lines. So maybe the value of $0 is leaking from zsh-d-so-fancy. Could you check there are no other f-sy-h related lines? 

Second, removing loading of zsh-diff-so-fancy might help f-sy-h.

**Comment by psprint** [comment]
Ok it appeared bright after some thinking – I've fixed the bug, it was in zsh-diff-so-fancy plugin. After you update `zdharma/zsh-diff-so-fancy` F-Sy-H should start working.

**Comment by BonaBeavis** [comment]
Works now. Thanks for your work!
