### ISSUE TITLE
User themes, colors' customization

### ISSUE THREAD

**Issue by psprint** [zdharma/fast-syntax-highlighting#49]
Current customization via `$FAST_HIGHLIGHT_STYLES` assignments is IMO not nice. Zshrc grows in size, the assignments can take half page or more, there's need for knowing FSH internals when using `$FAST_THEME_NAME` and constructing keys for the `*_STYLES` hash.

I'm thinking about `$XDG_CONFIG_HOME/fsh` overlay. A file in that dir, e.g. `free.ini`, would overwrite fields in the shipped theme `free`. User would edit INI file, which is IMO very good method, INI files are much readable and intuitive. Drawbacks – when moving with configuration to another account, not only copying of `.zshrc` would be needed, but also of additional files. Also, a run of `fast-theme` after each INI update would be needed.

Any thoughts on this? Maybe there is another method?

**Comment by plexigras** [comment]
Having a `custom.ini` file in the `themes` directory works great for me.

**Comment by psprint** [comment]
Playing around in plugin's dir is subject go Git collisions, so I cannot push this as general solution. That said, `custom.ini` is sure a comfortable solution, no "overlay" topics and imagining 2 filesystem locations.

**Comment by psprint** [comment]
PS. One of purposes of INI files is to encapsulate user's creativity so that at some point he has "a theme, that I can submit to upstream". So maybe "overlay" concept should be considered as an unwanted one.

**Comment by plexigras** [comment]
> Playing around in plugin's dir is subject to Git collisions

support for custom paths might be a solution to that  
so you can do `fast-theme ~/custom.ini` or something similar.

**Comment by psprint** [comment]
Hmm let me think about this. User would specify location of ini file at `fast-theme` run. This run is in general always needed when wanting to use a theme (can be avoided by copying pre-generated `current_theme.zsh` and `secondary_theme.zsh`), theme subsystem works this way, and there is no other place where this path would have to come up – this fact is important. It would be a big relief to not need to imagine 2 theme-locations and not let any overlay-like interaction. All this might in some part explain why `fast-theme ~/my/custom.ini` feels so natural and problem-free.

It might be that starting from this point, a hack-like (where thing is simple), not enterprise-like (where imagination and big-talk is needed) trick is possible: `fast-theme XDG:mytheme`. User would understand that he is supplying a path, by simple shorthand for `~/.config/fsh`, and that it's a full theme not an overlay.

All things apparently good, with one exception that overlay has it's possitive role, because user wants most of the time, at least at the beginning, to alter a few highlight styles, not many or all of them. So being still away from enterprise-concept-rich solution, XDG:overlay for `~/.config/fsh/overlay.ini` might be well functioning side to all above. `fast-theme XDG:overlay` would be a special call generating `theme_overlay.zsh`, with possible support for `fast-theme ~/overlay[.ini]` and other paths, i.e. only the filename `overlay[.ini]` would be treated specially, not a location.

**Comment by psprint** [comment]
I've coded what was described. Short description by possible uses:

```zsh
fast-theme XDG:custom
fast-theme OPT:mytheme
fast-theme XDG:overlay # will be treated specially because of name being "overlay"
fast-theme -R # remove overlay, deactivate it
```

I've added multiple path-shorthands, they are:

```zsh
XDG: = ${XDG_CONFIG_HOME:-$HOME/.config}/fsh/
LOCAL: = /usr/local/share/fsh/
HOME: = $HOME/.fsh/
OPT: = /opt/local/share/fsh/
```

Overlay can have only a few keys (styles).
