### ISSUE TITLE
Performance test

### ISSUE THREAD

**Issue by psprint** [zdharma/fast-syntax-highlighting#5]
@changyuheng, you wrote in other thread (https://github.com/zsh-users/zsh-history-substring-search/issues/58):

> The reason I don't want to enable zsh-syntax-highlighting is that it's performance is too bad. If you paste multiple lines of commands at once, your terminal would get stuck for a while which can be longer than 10 seconds.

Maybe you could test fast-syntax-highlighting here? It could solve the problem without limiting buffer's length to 100.

**Comment by changyuheng** [comment]
Still slow. Try to paste about 15 lines at once, you'll see the result.

**Comment by psprint** [comment]
It is fast for me. However I have updated autosuggestions, where they changed lately to asynchronous model. It showed to me to be a significant performance boost when pasting. Maybe you use autosuggestions too, and not current HEAD? That said, it is all slightly weird because in the other thread it was revealed that the `*MAXLENGTH` setting of z-sy-h did help

**Comment by changyuheng** [comment]
OK, it was my fault. Once I disabled this lib https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/misc.zsh, it's super fast. Thanks for helping!

**Comment by psprint** [comment]
n/p
