### ISSUE TITLE
commands in packages that aren't installed are highlighted as green

### ISSUE THREAD

**Issue by hoshsadiq** [zdharma/fast-syntax-highlighting#58]
Not sure what's causing this, but for some reason, commands in packages that aren't installed are showing up as green, as if it's installed. See below screenshot. Any ideas what might be causing this?

![image](https://user-images.githubusercontent.com/600045/44292703-3abf6180-a27e-11e8-997c-47418d291d80.png)

**Comment by psprint** [comment]
You might have an alias "tmux"? Try

```zsh
type -w tmux
which tmux
whence -v tmux
```

**Comment by hoshsadiq** [comment]
Nothing!

![image](https://user-images.githubusercontent.com/600045/44297801-9b2abf00-a2cf-11e8-8ffc-99c9b82f82ee.png)

**Comment by plexigras** [comment]
what about this?
```
echo "aliases:$+aliases[(e)tmux]
galiases:$+galiases[(e)tmux]
functions:$+functions[(e)tmux]
builtins:$+builtins[(e)tmux]
commands:$+commands[(e)tmux]
saliases:$+saliases[(e)tmux]"
```

**Comment by hoshsadiq** [comment]
```
 $ echo "aliases:$+aliases[(e)tmux]
galiases:$+galiases[(e)tmux]
functions:$+functions[(e)tmux]
builtins:$+builtins[(e)tmux]
commands:$+commands[(e)tmux]
saliases:$+saliases[(e)tmux]"
aliases:0
galiases:0
functions:0
builtins:0
commands:0
saliases:0
```

What's interesting is that it seems to be just tmux.
```

**Comment by plexigras** [comment]
found what's causing this

https://github.com/zdharma/fast-syntax-highlighting/blob/c599449ea46bd23b2095b43fca76f6d3443449bc/fast-highlight#L169

**Comment by hoshsadiq** [comment]
FYI that PR worked :) Thanks for the fix!
