### ISSUE TITLE
Respect to ANSI colors or betterize for light background

### ISSUE THREAD

**Issue by changyuheng** [zdharma/fast-syntax-highlighting#6]
I'm using solarized light color scheme. The current syntax highlighting for the variables is light green which is too light for my color scheme.

<img width="368" alt="screen shot 2017-04-14 at 10 54 50 am" src="https://cloud.githubusercontent.com/assets/1842626/25051310/cf09f36a-2100-11e7-9825-4048015d6ddd.png">

**Comment by psprint** [comment]
Current setting for variable is:

```zsh
FAST_HIGHLIGHT_STYLES[variable]="fg=112"
```

You can change it, using normal color names or 256 color numbers. All fields of `FAST_HIGHLIGHT_STYLES` hash that can be set are here: https://github.com/zdharma/fast-syntax-highlighting/blob/master/fast-highlight#L32-L58

**Comment by NightMachinary** [comment]
@changyuheng Did you create a good theme for solarized light? I also want such a thing. 
@psprint I think exposing a default theme for light backgrounds is a good idea. Current themes are all dark. I currently use the default theme, but it uses dark backgrounds sometimes:
![image](https://user-images.githubusercontent.com/36224762/81217265-8b966100-8ff1-11ea-899a-fca30baf927a.png)
