### ISSUE TITLE
Disable bold

### ISSUE THREAD

**Issue by karambaq** [zdharma/fast-syntax-highlighting#7]
Great plugin, but I have one question, how can I disable bold font when I start typing?

**Comment by psprint** [comment]
You can change color of `unknown-token` in `*STYLES` hash:

```zsh
FAST_HIGHLIGHT_STYLES[unknown-token]="fg=red"
```

This can be done before or after loading the plugin. Normally, the value is `fg=red,bold`:

https://github.com/zdharma/fast-syntax-highlighting/blob/6b07615a68936a074a04f709a2366d5c27faa762/fast-highlight#L32-L59

**Comment by karambaq** [comment]
@psprint Great, Thank you!

**Comment by HaleTom** [comment]
See #42 for customising colours if using a theme.
