### ISSUE TITLE
Aggregated various issues, (was: --foo="bar" no string highlighting for "bar")

### ISSUE THREAD

**Issue by plexigras** [zdharma/fast-syntax-highlighting#71]
just something i noticed :)

**Comment by plexigras** [comment]
another thing i noticed is the highlighting of `file` in `--foo=file`

**Comment by psprint** [comment]
I've noticed something today, of different category but I don't want to start a new issue:

```zsh
git tag -a 'v1.27' -m "Test tag" 24034b1
```

The commit hash isn't highlighted in the above.

**Comment by psprint** [comment]
Other thing from different category:

```zsh
fpath+=( ~/github/zplugin.git/doc ); autoload -Uz test-id-as
```

In the above the autoload function `test-id-as` will be highlighted as (subtle-)incorrect, because the whole line isn't yet executed and `$fpath` doesn't contain the needed directory.

A quick check shows something promising:
```zsh
buf='fpath+=( ~/github/zplugin.git/doc ); autoload'; printf '|%s|\n' "${(z@)buf}"; print
|fpath+=(|
|~/github/zplugin.git/doc|
|)|
|;|
|autoload|
```

So it looks like a new file `chroma/-fpath+=(.ch` and thus a new chroma is possible? It would add elements to e.g. `$FAST_HIGHLIGHT[immediate-fpath]` (side to that it would be passing-through everything), where value like `$HOME/github/zplugin.git/doc:/var/tmp` would be stored, which then would be used by `-autoload.ch` chroma, side to `$fpath`. It would be cleared in a `precmd` hook (i.e. it would work for current command line only).

**Comment by psprint** [comment]
3. `man ./zshall.1` highlights the argument as `incorrect-subtle` even though the file exists.

**Comment by psprint** [comment]
When e.g. (zargs fragment) `((end=ARGC+1))` occurs, it will highlight `end` in red, while as it is a variable that's being assigned, it doesn't have to exist, because it's being created.

**Comment by plexigras** [comment]
having a custom highlighter group for the `bar` part of `--foo=bar` could be a nice thing to have

**Comment by psprint** [comment]
So additional theme style/key? It doesn't sound very well at first, but then, when one recalls that coolness of F-Sy-H comes in a major way from **fine** granularity of the highlighting, then OK, let's push the style-set to the top 👍 The style could be: `option-equal-sign-value`.

I wonder if we could develop a way to recognize option-arguments in general, i.e. not only via equal sign. So e.g. in `git -c color.ui=yes fetch brancha:branchb`, we could detect that `color.ui=yes` is argument to `-C`, and apply the style `option-one-dash-value`, or maybe `option-one-dash-value-path`. To detect this, we could start building a database of options-with-arguments, in a form of a hash `local -A opt_map=( "git" "1c:1g;1C:1p", "make" "1C:1p;2old-file:=1p" )`, meaning:

 - git / `-c:1g` – one-dash option "c", one `general` argument,
 - git / `-C:1p` – one-dash option "C", one `path` argument
 - make / `-C:1p` – one-dash option "C", one `path` argument (identical to `git` above)
 - make / `--old-file:=1p` – two-dash option `old-file` (i.e. `--old-file`), with one `path` argument, **after equail-sign**.

Then, the big-loop could be learned to remember in `local last_option # e.g last_option="-C"`, `local last_value # e.g. last_value="/var/tmp/repo"` and query the hash with:

```zsh
local -A opt_styles=( "-1g" "option-one-dash-1st-value"
    "-1p" "option-one-dash-1st-path"
    "--1p" "option-two-dash-1st-path" )

if [[ "${main_db[$active_command]}" = (#b)"$last_option":(*) ]]; then
  if [[ "${match[1]}" = "$option_current_value_count"[a-z]## ]]; then 
    __style=${opt_styles[${last_option:%%[^-]##}${option_current_value_count}${main_db[$active_command]##*[0-9]##}]}
```

This doesn't handle the semicolon in `$main_db`, i.e. multiple option-defs per single command, but I've spend enough time on this already, it's fine as a starting point.

**Comment by psprint** [comment]
An update: `FPATH+=...` is tracked like `fpath+=( ...`, a single line of code made `FPATH+=...` compatible with `-fpath_peq.ch` chroma. Also, any `$VAR` inside the `fpath+=( $VAR/funs ...` or similar assignment is **EXPANDED**, i.e. `$HOME` will work, any other variable will also work. **TODO**: allow `${VAR}` syntax.

Presentation of the stuff: https://asciinema.org/a/208645
