### ISSUE TITLE
blue background everywhere

### ISSUE THREAD

**Issue by rebelot** [zdharma/fast-syntax-highlighting#78]
<img width="279" alt="screen shot 2018-09-02 at 00 39 11" src="https://user-images.githubusercontent.com/36300441/44950457-b574a900-ae48-11e8-821a-425ab9ee6ae3.png">

I don't think it's working as intended, or is it?

EDIT: it's default theme

**Comment by psprint** [comment]
It's expected, it signals that awk program doesn't have error, and that man page exists. Does it look bad?

**Comment by plexigras** [comment]
i think there could be made some improvements to the default theme

**Comment by psprint** [comment]
Maybe some quite invasive background-highlightings like the `awk` one could be made configurable.

@plexigras: what could be changed in the theme?
