### ISSUE TITLE
visual select[in vi mode]  style is broken.

### ISSUE THREAD

**Issue by grassofhust** [zdharma/fast-syntax-highlighting#8]
When quit visual select mode, background color is still there.

**Comment by grassofhust** [comment]
https://asciinema.org/a/AapzOZozVCjLjHz6tmgbOG4HD

**Comment by psprint** [comment]
It should be now fixed, thanks

**Comment by grassofhust** [comment]
It only works for visual select mode toggle, doesn't work for cursor movement.

``fast-syntax-highlighting`` vs ``zsh-syntax-highlighting``

https://asciinema.org/a/oTXWahmre1jSpfodpl46uNW1w

https://asciinema.org/a/Bk6ymAaDqjOB99bUaI2leAXGx

**Comment by psprint** [comment]
Fixed it, again thanks

**Comment by grassofhust** [comment]
Thanks.
