### ISSUE TITLE
zsh-autosuggestions suggestions highlighted incorrectly

### ISSUE THREAD

**Issue by jamerst** [zdharma/fast-syntax-highlighting#85]
The colour of the suggestions displayed by zsh-autosuggestions is overwritten by fast-syntax-highlighting to be white, which makes the suggestions less clear and more confusing.

I haven't found a workaround, and this issue isn't present in zsh-syntax-highlighting, so can this be fixed?

**Comment by psprint** [comment]
It's not present in newest F-Sy-H, after update the issue should go away

**Comment by jamerst** [comment]
So it is, thanks.
