### ISSUE TITLE
Rightmost character of visual selection not marked as expected (vi mode)

### ISSUE THREAD

**Issue by doubleloop** [zdharma/fast-syntax-highlighting#92]
```
$ zsh --version
zsh 5.6.2 (x86_64-debian-linux-gnu)
```

### Minimal `.zshrc`:
```
$ cat ~/.zshrc
bindkey -v
source ~/.oh-my-zsh-custom/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
```

### Steps to reproduce:
1. type `word1 word2 word3 word4`
1. press `esc` `0` `e` (position cursor on `1`)
1. press `v` `h` (start visual selection then move cursor left)
1. there is no visual indication that `1` is selected (it is in fact selected, you can press `d` to see that `d1` will be removed)

### Notes:
1. the issue apples only within first word (`word1` in above example)
1. the issue does not occur when you move cursor right
1. I found the same issue in zsh-users/zsh-syntax-highlighting
1. without the plugin, everything works as expected:

#### Without plugin (works as expected):
[![asciicast](https://asciinema.org/a/214694.svg)](https://asciinema.org/a/214694)

#### With plugin:
[![asciicast](https://asciinema.org/a/214693.svg)](https://asciinema.org/a/214693)

**Comment by psprint** [comment]
I'm attaching presentations of the bug:

Wrong behavior only for previously highlighted word/character:
![standout-wrong-1](https://user-images.githubusercontent.com/6049288/49566765-115d3b00-f92c-11e8-939b-8e5c6b0d45f2.gif)

Confirm that the problem is for previously highlighted word/character:
![standout-ok-2](https://user-images.githubusercontent.com/6049288/49566774-1621ef00-f92c-11e8-82b9-d6af76f5998b.gif)

**Comment by psprint** [comment]
I've fixed the rightmost-character issue. Turns out something within Zsh or somewhere else was blurring the viewport with additional inversed-character in the no-plugin case. Right most character from left-extending region wasn't highlighted at all, Zsh was adding highlighting to it.

**Comment by doubleloop** [comment]
Just tested the fix, now it works as expected. Thanks @psprint, closing the issue.

**Comment by psprint** [comment]
Thanks. @plexigras Could you check the behavior now, in urxvt?
