### ISSUE TITLE
Highlighting for git alias is incorrect

### ISSUE THREAD

**Issue by ysmood** [zdharma/fast-syntax-highlighting#94]
For example in `~/.gitconfig` set `[alias]` with `co = checkout`

the color of `co` below should be yellow, not be red:

![screen shot 2018-12-06 at 18 33 53](https://user-images.githubusercontent.com/1415488/49575244-93c61900-f985-11e8-94af-76a88d672de0.png)

**Comment by psprint** [comment]
I've commited the support for the git-aliases. It's simple, but should work in 80% of cases (the problem: aliases that are using options, the ones that a git-chroma analyzes to decide on the highlighting - currently they will be missed by git-chroma).

**Comment by jcrd** [comment]
This isn't working for me, I think because my git version (2.19.2) doesn't have an `alias` subcommand.

**Comment by ysmood** [comment]
@jcrd git alias was introduced years ago. may you should follow the doc https://git-scm.com/book/en/v2/Git-Basics-Git-Aliases

**Comment by jcrd** [comment]
@ysmood I was referring to the `git alias` command used [here](https://github.com/zdharma/fast-syntax-highlighting/commit/d0eeb2b18172c8e9061e2d0906493f1e3f8fc809#diff-fba8abe434b3dac2cf4c73b205d59b6bR80). As far as I can tell, it doesn't exist. Presumably the command `git config "alias.$__wrd"` should be used like it was [here](https://github.com/zdharma/fast-syntax-highlighting/commit/018b973a036c9fb39b62f1319ce1300654310a4c#diff-fba8abe434b3dac2cf4c73b205d59b6bR55).

**Comment by psprint** [comment]
Indeed, I've mistakenly used a custom command from `tj/git-extras` package. It's now replaced with `git config ...` invocation, output of which is then processed by Zshell script, and this is much faster, because external tools like `sed` or `sort` aren't invoked.

**Comment by jcrd** [comment]
Now it's working as expected.

**Comment by psprint** [comment]
@jcrd That's good, a luckily resolution (better performance) of this small but much surprising mistake ;) Thanks @ysmood  for reporting the idea.

**Comment by jcrd** [comment]
I realized _only_ aliases are being highlighted correctly. Now unaliased git subcommands are red.

**Comment by psprint** [comment]
> I realized _only_ aliases are being highlighted correctly. Now unaliased git subcommands are red.

I've wrote:
>> I think the reason is that you enter git commands outside git repository. But hey, this discovers a >> quite a bug – aliases outside git repository are highlighted as correct even though they cannot run.

It turns out the subcommands highlighting work fine here even if outside of a git repository:

Correct working of passing commands, not only aliases, **outside** a git repository:
![git-non-alias-cmds-2](https://user-images.githubusercontent.com/6049288/49763373-b9785880-fccc-11e8-8689-bb3138564334.png)

Correct working of passing commands, not only aliases, **inside** a git repository:
![git-non-alias-cmds](https://user-images.githubusercontent.com/6049288/49762891-66ea6c80-fccb-11e8-8c60-0278c7fd2696.png)


So could you test the issue somehow and provide some information about it? Because I rather don't have ideas of what can be wrong.

**Comment by psprint** [comment]
I've just added a commit (84e3094) that reorganizes, uplifts, shortens the code, could you check now?

**Comment by jcrd** [comment]
I don't know what was going wrong previously, but with the new commit both aliased and unaliased commands are highlighted correctly. Thanks!
