### ISSUE TITLE
add arg type for redirections 

### ISSUE THREAD

**Issue by plexigras** [zdharma/fast-syntax-highlighting#99]

**Comment by psprint** [comment]
I've browsed the source of `fast-highlight` and didn't found any traces of `<<<` being treated as arg type `3`. Does this mean that the title of this issue `<<< is not arg type 3` describes current status of the code and perceives it as a problem? I.e. `<<<` should be of arg-type `3`?

**Comment by plexigras** [comment]
yes

**Comment by plexigras** [comment]
![2018-12-29-233846_336x30_scrot](https://user-images.githubusercontent.com/8838132/50542648-df559680-0bc2-11e9-842c-66092a36478a.png)

they should not be highlighted red

**Comment by psprint** [comment]
The node chroma misses what `-git.ch` has, the `if in_redirection` block of code

**Comment by plexigras** [comment]
the git chroma is also still behaving weirdly

![2018-12-30-115830_103x30_scrot](https://user-images.githubusercontent.com/8838132/50546557-c8965a80-0c29-11e9-8046-eae6a4ce7a99.png)

**Comment by psprint** [comment]
I've extended the `node` chroma and the main chroma so that also `git` chroma works. Thanks!
